"""
ElderCare - Bank expansion generators.

Programmatically extends each curated core bank (diseases, medications,
activities, exercises) up to ~1000 entries while preserving the tag
vocabulary used by the optimizer. The original curated entries stay at
the top of each list (codes DIS001-015, MED001-015, etc.); expansions
take codes from a continuation range (DIS100+, MED100+, etc.).

All expansions are deterministic — same code always points to the same
row, so re-seeding is stable.
"""

from __future__ import annotations
import itertools


# ============================================================
# DISEASE EXPANSION
# ============================================================
# Each base: (he, en, category, limitations, needs, desc_he)
DISEASE_BASES = [
    # --- Cardiovascular ---
    ("יל\"ד", "Hypertension", "cardiovascular",
     "high_intensity;heavy_lifting;sudden_position_change",
     "aerobic_low;breathing;relaxation",
     "לחץ דם גבוה - הימנע ממאמץ קיצוני"),
    ("פרפור פרוזדורים", "Atrial Fibrillation", "cardiovascular",
     "high_intensity;sudden_position_change",
     "aerobic_low;breathing",
     "פרפור פרוזדורים - פעילות מתונה תחת השגחה"),
    ("אי ספיקת לב", "Heart Failure", "cardiovascular",
     "high_intensity;long_duration;hot_environment",
     "aerobic_very_low;breathing;monitored",
     "אי ספיקת לב - פעילות מתונה מאוד"),
    ("מחלת מסתמים", "Valvular Disease", "cardiovascular",
     "high_intensity;heavy_lifting",
     "aerobic_low;breathing",
     "מחלת מסתמים - הימנע ממאמץ כבד"),
    ("מחלת עורקים פריפריאלית", "Peripheral Artery Disease", "cardiovascular",
     "high_intensity;cold_air",
     "aerobic_low;daily_movement;gait_training",
     "מחלת עורקים בגפיים - הליכה מבוקרת"),
    ("פקקת ורידים עמוקה", "Deep Vein Thrombosis", "cardiovascular",
     "high_intensity;long_sitting",
     "daily_movement;range_of_motion",
     "פקקת ורידים - תנועה קלה בלבד"),
    ("תעוקת חזה יציבה", "Stable Angina", "cardiovascular",
     "high_intensity;cold_air",
     "aerobic_low;breathing;relaxation",
     "תעוקת חזה יציבה - פעילות מתונה"),
    ("פוסט אוטם שריר הלב", "Post-MI", "cardiovascular",
     "high_intensity;heavy_lifting;hot_environment",
     "aerobic_low;breathing;monitored;relaxation",
     "לאחר אוטם - שיקום לבבי הדרגתי"),
    ("קרדיומיופתיה", "Cardiomyopathy", "cardiovascular",
     "high_intensity;long_duration",
     "aerobic_very_low;breathing;monitored",
     "קרדיומיופתיה - פעילות תחת מעקב"),
    ("הפרעת קצב", "Arrhythmia", "cardiovascular",
     "high_intensity;sudden_position_change",
     "aerobic_low;breathing;relaxation",
     "הפרעת קצב - פעילות מתונה"),
    ("עילפון חוזר", "Recurrent Syncope", "cardiovascular",
     "high_balance_demand;sudden_position_change",
     "balance;hydration;structured_routine",
     "עילפון חוזר - הימנע משינוי תנוחה פתאומי"),

    # --- Endocrine/Metabolic ---
    ("סוכרת סוג 1", "Type 1 Diabetes", "metabolic",
     "high_intensity_long_fast",
     "aerobic_low;balanced_diet;daily_movement;structured_routine",
     "סוכרת סוג 1 - ניטור סוכר לפני ואחרי פעילות"),
    ("סוכרת סוג 2", "Type 2 Diabetes", "metabolic",
     "high_intensity_long_fast;sugar_rich_food",
     "aerobic_low;balanced_diet;daily_movement",
     "סוכרת סוג 2 - פעילות מתונה קבועה"),
    ("תת-תריס", "Hypothyroidism", "metabolic",
     "high_intensity",
     "aerobic_low;daily_movement;relaxation",
     "תת פעילות בלוטת התריס - עייפות, פעילות הדרגתית"),
    ("יתר-תריס", "Hyperthyroidism", "metabolic",
     "high_intensity;hot_environment",
     "relaxation;breathing;aerobic_low",
     "יתר פעילות בלוטת התריס - הימנע ממאמץ ולחום"),
    ("דיסליפידמיה", "Dyslipidemia", "metabolic",
     "extreme_endurance",
     "aerobic_low;daily_movement;balanced_diet",
     "כולסטרול גבוה - פעילות אירובית, תזונה"),
    ("שיגדון (גאוט)", "Gout", "metabolic",
     "high_impact",
     "swimming;water_aerobics;range_of_motion",
     "שיגדון - הימנע מעומס על מפרק נגוע"),
    ("השמנת יתר", "Obesity", "metabolic",
     "high_impact;high_intensity",
     "aerobic_low;swimming;water_aerobics;balanced_diet;daily_movement",
     "השמנת יתר - אירובי בהדרגה, מים מומלץ"),
    ("תת תזונה", "Malnutrition", "metabolic",
     "high_intensity;extreme_endurance",
     "balanced_diet;aerobic_low;daily_movement",
     "תת תזונה - מאמץ מתון, חיזוק תזונתי"),

    # --- Musculoskeletal ---
    ("אוסטאוארתריטיס ברך", "Knee Osteoarthritis", "musculoskeletal",
     "running;jumping;deep_squat;stairs_high",
     "swimming;water_aerobics;quadriceps_strength;range_of_motion",
     "שחיקת ברך - מים, חיזוק שריר ירך"),
    ("אוסטאוארתריטיס ירך", "Hip Osteoarthritis", "musculoskeletal",
     "running;jumping;deep_squat;stairs_high",
     "swimming;water_aerobics;quadriceps_strength;range_of_motion;balance",
     "שחיקת ירך - מים, חיזוק"),
    ("אוסטאוארתריטיס עמוד שדרה", "Spinal Osteoarthritis", "musculoskeletal",
     "heavy_lifting;high_impact",
     "range_of_motion;upper_body_low;flexibility",
     "שחיקת עמוד שדרה - גמישות, חיזוק עדין"),
    ("אוסטאוארתריטיס יד", "Hand Osteoarthritis", "musculoskeletal",
     "heavy_lifting;grip_intensive",
     "range_of_motion;fine_motor;flexibility",
     "שחיקת יד - מוטוריקה עדינה"),
    ("שחיקת כתף", "Shoulder Osteoarthritis", "musculoskeletal",
     "heavy_lifting;overhead_motion",
     "range_of_motion;upper_body_low;flexibility",
     "שחיקת כתף - גמישות, חיזוק עדין"),
    ("דלקת מפרקים שגרונית", "Rheumatoid Arthritis", "musculoskeletal",
     "high_impact;heavy_lifting",
     "swimming;water_aerobics;range_of_motion;flexibility",
     "RA - מים, גמישות, חיזוק קל"),
    ("אוסטאופורוזיס", "Osteoporosis", "musculoskeletal",
     "high_impact;jumping;contact_sport;falls_risk",
     "weight_bearing_low;balance;flexibility",
     "דלדול עצמות - נשיאת משקל, איזון"),
    ("שבר חולייתי", "Vertebral Fracture", "musculoskeletal",
     "heavy_lifting;high_impact;jumping",
     "weight_bearing_low;range_of_motion;upper_body_low",
     "שבר חולייתי - מנוחה ושיקום הדרגתי"),
    ("שבר ירך", "Hip Fracture", "musculoskeletal",
     "high_impact;running;deep_squat;heavy_lifting",
     "weight_bearing_low;balance;gait_training;quadriceps_strength",
     "שבר ירך - שיקום, איזון, הליכה"),
    ("קרע גיד מסובב", "Rotator Cuff Tear", "musculoskeletal",
     "heavy_lifting;overhead_motion",
     "range_of_motion;upper_body_low",
     "קרע בכתף - שיקום הדרגתי"),
    ("היצרות עמוד שדרה מותני", "Lumbar Stenosis", "musculoskeletal",
     "high_impact;long_standing",
     "swimming;water_aerobics;flexibility",
     "היצרות מותנית - מים, גמישות"),

    # --- Neurological ---
    ("אלצהיימר קל", "Mild Alzheimer's", "neurological",
     "complex_instructions;new_environment_alone;unsupervised",
     "memory_games;routine;reminiscence;social_engagement",
     "אלצהיימר קל - גירוי קוגניטיבי, שגרה"),
    ("דמנציה בינונית", "Moderate Dementia", "neurological",
     "complex_instructions;new_environment_alone;multi_step_tasks;unsupervised",
     "simple_routine;music_therapy;sensory_stim;reminiscence",
     "דמנציה בינונית - גרייה חושית, מוסיקה"),
    ("דמנציה חמורה", "Severe Dementia", "neurological",
     "complex_instructions;unsupervised;new_environment_alone",
     "sensory_stim;music;familiar_objects;passive_motion",
     "דמנציה חמורה - גרייה חושית בסיסית"),
    ("דמנציה וסקולרית", "Vascular Dementia", "neurological",
     "complex_instructions;new_environment_alone",
     "simple_routine;memory_games;social_engagement",
     "דמנציה וסקולרית - שגרה ומבנה"),
    ("דמנציית גופי לואי", "Lewy Body Dementia", "neurological",
     "complex_instructions;high_balance_demand",
     "simple_routine;memory_games;sensory_stim",
     "דמנציית גופי לואי - הזיות ושינויים בערנות"),
    ("דמנציה פרונטו-טמפורלית", "Frontotemporal Dementia", "neurological",
     "complex_instructions;new_environment_alone",
     "structured_routine;simple_routine",
     "דמנציה פרונטו-טמפורלית - שינויים בהתנהגות"),
    ("פרקינסון", "Parkinson's", "neurological",
     "high_balance_demand;fast_changes;crowded_space",
     "balance;rhythmic_movement;gait_training;voice_exercise;flexibility",
     "פרקינסון - איזון, ריתמוס"),
    ("פרקינסוניזם", "Parkinsonism", "neurological",
     "high_balance_demand;fast_changes",
     "balance;rhythmic_movement;gait_training",
     "פרקינסוניזם - דומה לפרקינסון"),
    ("פוסט שבץ", "Post-Stroke", "neurological",
     "high_intensity;complex_motor;unsupervised",
     "physiotherapy;speech_therapy;range_of_motion;mirror_therapy",
     "אחרי שבץ - פיזיו, ריפוי דיבור"),
    ("התקף איסכמי חולף", "TIA", "neurological",
     "high_intensity",
     "aerobic_low;monitored;structured_routine",
     "TIA - פעילות מתונה, מעקב"),
    ("נוירופתיה פריפריאלית", "Peripheral Neuropathy", "neurological",
     "high_balance_demand;sharp_tools",
     "balance;range_of_motion;sensory_stim",
     "נוירופתיה - תחושה לקויה ברגליים"),
    ("טרשת נפוצה", "Multiple Sclerosis", "neurological",
     "high_intensity;hot_environment;fatigue_triggers",
     "aerobic_low;range_of_motion;balance;breathing",
     "טרשת נפוצה - הימנע מחום ועייפות"),
    ("רעד חיוני", "Essential Tremor", "neurological",
     "fine_motor_precise",
     "range_of_motion;relaxation;mindfulness",
     "רעד חיוני - תנועה רכה, הרפיה"),
    ("הידרוצפלוס בלחץ נורמלי", "NPH", "neurological",
     "high_balance_demand",
     "balance;gait_training;range_of_motion",
     "הידרוצפלוס - הפרעות הליכה ושיווי משקל"),

    # --- Psychiatric ---
    ("דיכאון קליני", "Major Depression", "mental",
     "isolation;over_stimulation",
     "social;light_exposure;aerobic_low;structured_routine;creative",
     "דיכאון - חיבור חברתי, אור, יצירה"),
    ("דיכאון מתמשך", "Persistent Depressive Disorder", "mental",
     "isolation",
     "social;structured_routine;aerobic_low",
     "דיסטימיה - שגרה ומעורבות"),
    ("חרדה כללית", "Generalized Anxiety", "mental",
     "loud_crowds;competitive;time_pressure",
     "breathing;mindfulness;yoga;nature_exposure;art_therapy",
     "חרדה - נשימה, מיינדפולנס"),
    ("הפרעת פאניקה", "Panic Disorder", "mental",
     "loud_crowds;crowded_space;high_intensity",
     "breathing;mindfulness;relaxation",
     "התקפי פאניקה - הרפיה ונשימה"),
    ("פוסט טראומה", "PTSD", "mental",
     "trigger_topics;loud_crowds;authoritarian_settings",
     "mindfulness;breathing;creative;social",
     "פוסט טראומה - הימנע מטריגרים"),
    ("OCD", "OCD", "mental",
     "competitive;time_pressure",
     "mindfulness;structured_routine;creative",
     "טורדני-כפייתי - שגרה ומיינדפולנס"),
    ("הפרעה דו-קוטבית", "Bipolar Disorder", "mental",
     "isolation;over_stimulation;sleep_disruption",
     "structured_routine;social;mindfulness",
     "דו-קוטבית - שגרה ויציבות"),
    ("פסיכוזה זקנה", "Late-life Psychosis", "mental",
     "over_stimulation;loud_crowds",
     "structured_routine;sensory_stim;mindfulness",
     "פסיכוזה - סביבה רגועה ומובנת"),
    ("הפרעת שינה", "Sleep Disorder", "mental",
     "evening_caffeine",
     "structured_routine;light_exposure;aerobic_low;breathing",
     "הפרעת שינה - שגרה ופעילות אירובית"),
    ("דליריום (מצב הזיות זמני)", "Delirium", "mental",
     "complex_instructions;new_environment_alone;over_stimulation",
     "structured_routine;sensory_stim;hydration",
     "דליריום - סביבה מוכרת, שגרה"),

    # --- Sensory ---
    ("ירידה בשמיעה (פרסביכוזיס)", "Presbycusis", "sensory",
     "audio_only_activities;noisy_environment",
     "visual_cues;small_group;subtitles",
     "ירידת שמיעה זקנה - תוכן חזותי"),
    ("חירשות סנסורי-נוירלית", "Sensorineural Hearing Loss", "sensory",
     "audio_only_activities;noisy_environment",
     "visual_cues;sign_supported;subtitles",
     "חירשות עצבית"),
    ("פרסביופיה", "Presbyopia", "sensory",
     "reading_small",
     "large_print;audio_based",
     "ראייה זקנה - הדפסה מוגדלת"),
    ("ניוון מקולה יבש", "Dry AMD", "sensory",
     "visual_only_activities;poor_lighting;reading_small",
     "audio_based;tactile;large_print",
     "ניוון מקולה יבש"),
    ("ניוון מקולה רטוב", "Wet AMD", "sensory",
     "visual_only_activities;poor_lighting;reading_small",
     "audio_based;tactile;large_print",
     "ניוון מקולה רטוב"),
    ("גלאוקומה", "Glaucoma", "sensory",
     "visual_only_activities;poor_lighting",
     "audio_based;tactile",
     "גלאוקומה - לחץ עין"),
    ("קטרקט", "Cataract", "sensory",
     "visual_only_activities;poor_lighting",
     "audio_based;large_print",
     "קטרקט - ירידת ראייה"),
    ("עין יבשה", "Dry Eye", "sensory",
     "dusty_environment;long_screen_use",
     "hydration;breaks",
     "עין יבשה - הימנע מאוויר יבש"),

    # --- Respiratory ---
    ("COPD", "COPD", "respiratory",
     "high_intensity;cold_air;dusty_environment",
     "breathing;pursed_lip;upper_body_low;walk_short",
     "מחלת ריאות חסימתית"),
    ("אסטמה", "Asthma", "respiratory",
     "high_intensity;cold_air;dusty_environment",
     "breathing;pursed_lip;aerobic_low",
     "אסטמה - הימנע מטריגרים"),
    ("דום נשימה בשינה (OSA)", "OSA", "respiratory",
     "evening_meals",
     "aerobic_low;weight_loss;breathing",
     "דום נשימה בשינה"),
    ("פיברוזיס ריאתי", "Pulmonary Fibrosis", "respiratory",
     "high_intensity;dusty_environment",
     "breathing;pursed_lip;aerobic_very_low",
     "פיברוזיס ריאתי - פעילות מאוד מתונה"),
    ("שיקום אחרי דלקת ריאות", "Pneumonia Recovery", "respiratory",
     "high_intensity;cold_air",
     "breathing;pursed_lip;aerobic_low",
     "שיקום מדלקת ריאות"),

    # --- Renal/Urological ---
    ("מחלת כליות כרונית", "Chronic Kidney Disease", "renal",
     "high_intensity;high_protein",
     "aerobic_low;balanced_diet;hydration",
     "אי ספיקת כליות"),
    ("דיאליזה", "On Dialysis", "renal",
     "high_intensity;long_duration",
     "aerobic_very_low;monitored;balanced_diet",
     "מטופל דיאליזה"),
    ("היפרטרופיה שפירה של ערמונית", "BPH", "urological",
     "long_no_bathroom_access",
     "timed_voiding;pelvic_floor",
     "ערמונית מוגדלת"),
    ("בריחת שתן במאמץ", "Stress Incontinence", "urological",
     "long_no_bathroom_access;high_impact",
     "pelvic_floor;timed_voiding",
     "בריחת שתן במאמץ"),
    ("בריחת שתן דחופה", "Urge Incontinence", "urological",
     "long_no_bathroom_access",
     "timed_voiding;pelvic_floor;mindfulness",
     "בריחת שתן דחופה"),
    ("בריחת שתן מעורבת", "Mixed Incontinence", "urological",
     "long_no_bathroom_access;high_impact",
     "pelvic_floor;timed_voiding",
     "בריחת שתן מעורבת"),

    # --- GI ---
    ("רפלוקס (GERD)", "GERD", "gastrointestinal",
     "evening_meals;lying_after_meal",
     "balanced_diet;structured_routine",
     "רפלוקס - שינויי הרגלים"),
    ("תסמונת מעי רגיז", "IBS", "gastrointestinal",
     "stress",
     "mindfulness;balanced_diet;structured_routine",
     "IBS - הפחתת מתח"),
    ("מחלת מעי דלקתית", "IBD", "gastrointestinal",
     "high_intensity",
     "aerobic_low;balanced_diet;mindfulness",
     "IBD - פעילות מתונה"),
    ("דיברטיקולוזיס", "Diverticular Disease", "gastrointestinal",
     "heavy_lifting",
     "aerobic_low;balanced_diet",
     "דיברטיקולוזיס"),

    # --- Cancer ---
    ("סרטן שד - שיקום", "Breast Cancer Recovery", "oncology",
     "heavy_lifting;hot_environment",
     "aerobic_low;range_of_motion;creative;social",
     "סרטן שד - שיקום"),
    ("סרטן ערמונית", "Prostate Cancer", "oncology",
     "high_intensity",
     "aerobic_low;pelvic_floor;mindfulness",
     "סרטן ערמונית"),
    ("סרטן מעי הגס", "Colorectal Cancer", "oncology",
     "heavy_lifting",
     "aerobic_low;balanced_diet",
     "סרטן מעי הגס"),
    ("סרטן ריאה", "Lung Cancer", "oncology",
     "high_intensity;cold_air",
     "breathing;aerobic_very_low",
     "סרטן ריאה"),
    ("לימפומה", "Lymphoma", "oncology",
     "high_intensity",
     "aerobic_low;mindfulness;balanced_diet",
     "לימפומה"),

    # --- Skin/Other ---
    ("פצעי לחץ", "Pressure Ulcers", "skin",
     "long_sitting;long_lying",
     "range_of_motion;passive_motion;repositioning",
     "פצעי לחץ - תזוזה תכופה"),
    ("הרפס זוסטר", "Shingles", "skin",
     "high_intensity",
     "relaxation;mindfulness;aerobic_low",
     "שלבקת חוגרת"),
    ("נוירלגיה פוסט-הרפטית", "Post-Herpetic Neuralgia", "neurological",
     "high_intensity",
     "mindfulness;relaxation;range_of_motion",
     "כאב לאחר שלבקת חוגרת"),

    # --- Frailty/Geriatric ---
    ("סרקופניה", "Sarcopenia", "geriatric",
     "high_impact",
     "weight_bearing_low;balance;quadriceps_strength;daily_movement",
     "אובדן מסת שריר"),
    ("תסמונת שבריריות", "Frailty Syndrome", "geriatric",
     "high_intensity;high_impact",
     "aerobic_low;balance;quadriceps_strength;balanced_diet",
     "תסמונת שבריריות"),
    ("נופלים חוזרים", "Recurrent Falls", "geriatric",
     "high_balance_demand;unsupervised",
     "balance;gait_training;weight_bearing_low",
     "נפילות חוזרות"),
    ("חסר ויטמין D", "Vitamin D Deficiency", "geriatric",
     "",
     "light_exposure;weight_bearing_low;balanced_diet",
     "חסר ויטמין D"),
    ("אנמיה זקנה", "Anemia of Aging", "geriatric",
     "high_intensity",
     "aerobic_low;balanced_diet",
     "אנמיה"),
    ("ירידה תפקודית", "Functional Decline", "geriatric",
     "high_intensity",
     "daily_movement;quadriceps_strength;range_of_motion",
     "ירידה תפקודית"),
]


SEVERITY_VARIANTS = [
    ("קל", "Mild"), ("בינוני", "Moderate"), ("חמור", "Severe"),
    ("מאוזן", "Controlled"), ("לא מאוזן", "Uncontrolled"),
    ("יציב", "Stable"), ("בהתקדמות", "Progressive"),
    ("שלב מוקדם", "Early Stage"), ("שלב מתקדם", "Advanced Stage"),
    ("הישנות", "Relapsing"),
]


def expand_diseases(core: list) -> list:
    """Return core + ~985 expansions for a total of ~1000 diseases."""
    out = list(core)
    counter = 100
    for base in DISEASE_BASES:
        base_he, base_en, cat, lims, needs, desc = base
        for sev_he, sev_en in SEVERITY_VARIANTS:
            if counter >= 1000 - len(core) + 100:
                break
            code = f"DIS{counter:03d}"
            counter += 1
            out.append((
                code,
                f"{base_he} - {sev_he}",
                f"{base_en} - {sev_en}",
                cat,
                lims,
                needs,
                desc,
            ))
        if len(out) >= 1000:
            break
    return out[:1000]


# ============================================================
# MEDICATION EXPANSION
# ============================================================
MED_BASES = [
    # (he, en, drug_class, side_effects, contraindications, needs, desc)
    ("מטפורמין", "Metformin", "antidiabetic",
     "gi_upset;mild_fatigue", "high_intensity_long_fast",
     "aerobic_low;daily_movement", "סוכרת"),
    ("גליפלוזין", "SGLT2 Inhibitor", "antidiabetic",
     "uti_risk;hypotension", "long_no_bathroom_access",
     "aerobic_low;hydration", "סוכרת"),
    ("GLP-1", "GLP-1 Agonist", "antidiabetic",
     "gi_upset;nausea", "",
     "aerobic_low;balanced_diet;daily_movement", "סוכרת"),
    ("אינסולין", "Insulin", "antidiabetic",
     "hypoglycemia_risk", "high_intensity_long_fast",
     "aerobic_low;balanced_diet;monitored", "סוכרת"),
    ("סטטין", "Statin", "lipid_lowering",
     "muscle_pain;fatigue", "extreme_endurance",
     "aerobic_low", "ירידת כולסטרול"),
    ("פיברט", "Fibrate", "lipid_lowering",
     "muscle_pain;gi_upset", "",
     "aerobic_low;balanced_diet", "טריגליצרידים"),
    ("ACE inhibitor", "ACE Inhibitor", "antihypertensive",
     "dizziness;dry_cough", "sudden_position_change",
     "aerobic_low;breathing", "לחץ דם"),
    ("ARB", "ARB", "antihypertensive",
     "dizziness", "sudden_position_change",
     "aerobic_low;breathing", "לחץ דם"),
    ("בטא בלוקר", "Beta Blocker", "antihypertensive",
     "fatigue;low_hr", "high_intensity",
     "aerobic_low;breathing", "לחץ דם/לב"),
    ("חוסם תעלות סידן", "Calcium Channel Blocker", "antihypertensive",
     "edema;dizziness", "sudden_position_change",
     "aerobic_low;balance", "לחץ דם"),
    ("משתן תיאזידי", "Thiazide Diuretic", "diuretic",
     "dehydration;hyponatremia", "long_no_bathroom_access;hot_environment",
     "hydration;balanced_diet;timed_voiding", "לחץ דם"),
    ("משתן לולאה", "Loop Diuretic", "diuretic",
     "dehydration;electrolyte_imbalance", "long_no_bathroom_access;hot_environment",
     "hydration;balanced_diet;timed_voiding;aerobic_very_low", "אי ספיקת לב"),
    ("דיגוקסין", "Digoxin", "cardiac",
     "nausea;visual_disturbance", "high_intensity",
     "aerobic_low;balanced_diet", "אי ספיקת לב/קצב"),
    ("וורפרין", "Warfarin", "anticoagulant",
     "bleeding_risk;bruising", "contact_sport;high_fall_risk;sharp_tools",
     "balance;gait_training", "מדלל דם"),
    ("DOAC", "DOAC", "anticoagulant",
     "bleeding_risk", "contact_sport;high_fall_risk",
     "balance", "מדלל דם דור חדש"),
    ("אספירין", "Aspirin", "antiplatelet",
     "bleeding_risk_mild;gi_upset", "contact_sport",
     "aerobic_low;daily_movement;balanced_diet", "מניעת קרישים"),
    ("קלופידוגרל", "Clopidogrel", "antiplatelet",
     "bleeding_risk", "contact_sport;sharp_tools",
     "aerobic_low;balance", "מניעת קרישים"),
    ("SSRI", "SSRI", "antidepressant",
     "gi_upset;sleep_changes", "",
     "social;aerobic_low;light_exposure", "דיכאון"),
    ("SNRI", "SNRI", "antidepressant",
     "blood_pressure_rise;sleep_changes", "",
     "social;aerobic_low", "דיכאון/כאב"),
    ("טריציקלי", "Tricyclic Antidepressant", "antidepressant",
     "dry_mouth;orthostatic;sedation", "high_balance_demand;sudden_position_change",
     "hydration;balance", "דיכאון/כאב"),
    ("בנזודיאזפינים", "Benzodiazepines", "anxiolytic",
     "sedation;fall_risk;cognitive_blunting", "high_balance_demand;complex_cognitive",
     "balance;mindfulness;breathing", "חרדה/שינה"),
    ("בוספירון", "Buspirone", "anxiolytic",
     "dizziness", "",
     "mindfulness;breathing", "חרדה"),
    ("אנטיפסיכוטי לא טיפוסי", "Atypical Antipsychotic", "antipsychotic",
     "weight_gain;metabolic;sedation", "high_balance_demand",
     "balance;balanced_diet", "פסיכוזה/אי שקט"),
    ("ל-דופא", "Levodopa", "antiparkinson",
     "dyskinesia;orthostatic_drop;sleepiness", "high_balance_demand_when_off",
     "balance;voice_exercise;gait_training", "פרקינסון"),
    ("מעכב MAO-B", "MAO-B Inhibitor", "antiparkinson",
     "insomnia", "",
     "balance;gait_training", "פרקינסון"),
    ("דונפזיל", "Donepezil", "cholinesterase_inhibitor",
     "gi_upset;sleep_disturbance", "",
     "memory_games;moderate_cognitive", "אלצהיימר"),
    ("ריבסטיגמין", "Rivastigmine", "cholinesterase_inhibitor",
     "gi_upset;weight_loss", "",
     "memory_games;balanced_diet", "אלצהיימר"),
    ("ממנטין", "Memantine", "nmda_antagonist",
     "dizziness;confusion", "high_balance_demand",
     "memory_games;sensory_stim", "דמנציה מתקדמת"),
    ("PPI", "PPI", "gi_acid",
     "b12_deficiency", "",
     "balanced_diet;weight_bearing_low", "רפלוקס/כיב"),
    ("חוסם H2", "H2 Blocker", "gi_acid",
     "confusion_elderly", "",
     "balanced_diet;structured_routine", "רפלוקס"),
    ("פרצטמול", "Acetaminophen", "analgesic",
     "liver_caution_doses", "",
     "mindfulness;range_of_motion;daily_movement", "כאב קל"),
    ("NSAID", "NSAID", "analgesic",
     "gi_upset;renal_risk", "",
     "balanced_diet;hydration;range_of_motion", "כאב/דלקת"),
    ("טרמדול", "Tramadol", "analgesic",
     "sedation;confusion;serotonin_risk", "high_balance_demand;complex_cognitive",
     "balance", "כאב בינוני"),
    ("אופיואיד חזק", "Strong Opioid", "analgesic",
     "sedation;constipation;balance_impairment", "high_balance_demand;high_intensity",
     "balance;hydration", "כאב חזק"),
    ("ויטמין D", "Vitamin D", "supplement",
     "", "",
     "weight_bearing_low;light_exposure", "תוספת"),
    ("סידן", "Calcium", "supplement",
     "constipation", "",
     "weight_bearing_low", "תוספת"),
    ("ביספוספונט", "Bisphosphonate", "bone_density",
     "gi_upset;esophagitis", "lying_after_meal",
     "weight_bearing_low;balance", "אוסטאופורוזיס"),
    ("דנוסומאב", "Denosumab", "bone_density",
     "hypocalcemia", "",
     "weight_bearing_low;balance", "אוסטאופורוזיס"),
    ("חיסונים", "Vaccines", "preventive",
     "soreness", "",
     "social;structured_routine;daily_movement", "מניעה"),
    ("חסם בטא בעין", "Topical Beta Blocker", "ophthalmic",
     "systemic_effects", "",
     "structured_routine;audio_based", "גלאוקומה"),
    ("פרוסטגלנדין בעין", "Prostaglandin Eye Drops", "ophthalmic",
     "iris_color_change", "",
     "structured_routine", "גלאוקומה"),
    ("ברונכודילטור קצר טווח", "Short-acting Bronchodilator", "respiratory",
     "tachycardia;tremor", "",
     "breathing;pursed_lip", "אסטמה/COPD"),
    ("ברונכודילטור ארוך טווח", "Long-acting Bronchodilator", "respiratory",
     "tachycardia;dry_mouth", "",
     "breathing;pursed_lip;aerobic_low", "COPD"),
    ("סטרואיד בשאיפה", "Inhaled Steroid", "respiratory",
     "oral_thrush;hoarseness", "",
     "breathing;voice_exercise", "אסטמה"),
    ("הורמון תיריס", "Thyroid Hormone", "hormone",
     "tachycardia_overdose", "",
     "balanced_diet", "תת-תריס"),
    ("חוסם ערמונית", "Alpha Blocker", "urological",
     "orthostatic", "sudden_position_change",
     "balance", "ערמונית"),
    ("אנטי-מוסקריני", "Anticholinergic", "urological",
     "dry_mouth;confusion", "complex_cognitive",
     "timed_voiding;hydration", "בריחת שתן"),
    ("מירטזפין", "Mirtazapine", "antidepressant",
     "sedation;weight_gain", "",
     "social;balanced_diet", "דיכאון/שינה"),
    ("טרזודון", "Trazodone", "sleep_aid",
     "sedation;orthostatic", "high_balance_demand;sudden_position_change",
     "balance;structured_routine", "שינה"),
    ("מלטונין", "Melatonin", "sleep_aid",
     "morning_grogginess", "",
     "structured_routine;light_exposure", "שינה"),
]


MED_FORM_VARIANTS = [
    ("טבליה", "Tablet"), ("כמוסה", "Capsule"),
    ("נוזל פומי", "Oral Solution"), ("טבליה משחררת ממושכת", "Extended-Release"),
    ("מינון נמוך", "Low Dose"), ("מינון בינוני", "Mid Dose"),
    ("מינון גבוה", "High Dose"), ("פעם ביום", "Once Daily"),
    ("פעמיים ביום", "Twice Daily"), ("שלוש פעמים ביום", "Three Times Daily"),
    ("מוצק", "Patch"), ("זריקה", "Injectable"),
    ("מינון התחלתי", "Starting Dose"), ("מינון תחזוקה", "Maintenance Dose"),
    ("מינון לדיירים", "Elderly Dose"), ("מינון מותאם כליות", "Renal-Adjusted"),
    ("מינון מותאם כבד", "Hepatic-Adjusted"), ("גנרי", "Generic"),
    ("מותג מקורי", "Brand"), ("שילוב", "Combination"),
]


def expand_medications(core: list) -> list:
    out = list(core)
    counter = 100
    for base in MED_BASES:
        base_he, base_en, cls, side, contras, needs, desc = base
        for form_he, form_en in MED_FORM_VARIANTS:
            code = f"MED{counter:03d}"
            counter += 1
            out.append((
                code,
                f"{base_he} - {form_he}",
                f"{base_en} - {form_en}",
                cls,
                side,
                contras,
                needs,
                desc,
            ))
            if len(out) >= 1000:
                return out[:1000]
    return out[:1000]


# ============================================================
# ACTIVITY EXPANSION
# ============================================================
ACTIVITY_BASES = [
    # (he, en, category, subcat, strengthens, contras, min_cap, dur, gmin, gmax, location, desc)
    ("הליכה", "Walking", "physical", "aerobic",
     "aerobic_low;social;light_exposure;daily_movement", "",
     2, 30, 1, 12, "outdoor", "הליכה"),
    ("התעמלות בכיסא", "Chair Exercise", "physical", "strength_flex",
     "range_of_motion;upper_body_low;quadriceps_strength;flexibility", "",
     1, 25, 1, 20, "indoor", "תרגילים בכיסא"),
    ("פעילות במים", "Water Activity", "physical", "aerobic",
     "swimming;water_aerobics;quadriceps_strength;range_of_motion;aerobic_low", "",
     2, 40, 1, 15, "indoor", "פעילות במים"),
    ("איזון ויציבה", "Balance Training", "physical", "balance",
     "balance;weight_bearing_low;gait_training;flexibility", "",
     2, 20, 1, 10, "indoor", "איזון"),
    ("טאי צ'י", "Tai Chi", "physical", "mind_body",
     "balance;rhythmic_movement;flexibility;mindfulness;breathing;relaxation", "",
     2, 45, 1, 15, "indoor", "טאי צ'י"),
    ("יוגה", "Yoga", "physical", "mind_body",
     "flexibility;breathing;relaxation;yoga;mindfulness;range_of_motion", "",
     2, 45, 1, 15, "indoor", "יוגה"),
    ("נשימה ומדיטציה", "Breathing & Meditation", "mental", "meditation",
     "breathing;mindfulness;relaxation;pursed_lip", "",
     1, 20, 1, 15, "indoor", "נשימה"),
    ("דיבור וקול", "Speech & Voice", "physical", "speech",
     "speech_therapy;voice_exercise", "",
     1, 20, 1, 8, "indoor", "תרגילי דיבור"),
    ("משחקי זיכרון", "Memory Games", "cognitive", "memory",
     "memory_games;moderate_cognitive;complex_cognitive;learning_new", "complex_instructions",
     2, 30, 1, 10, "indoor", "זיכרון"),
    ("פאזלים", "Puzzles", "cognitive", "problem_solving",
     "moderate_cognitive;complex_cognitive", "complex_instructions",
     2, 30, 1, 5, "indoor", "פאזלים"),
    ("רמיניסנציה", "Reminiscence", "cognitive", "memory",
     "reminiscence;reminiscence_careful;social;memory_games", "trigger_topics",
     1, 45, 1, 10, "indoor", "סיפורי עבר"),
    ("אומנות", "Art", "cognitive", "creative",
     "creative;art_therapy;mindfulness;social", "",
     1, 60, 1, 12, "indoor", "אומנות"),
    ("מוסיקה", "Music", "cognitive", "music",
     "music_therapy;voice_exercise;rhythmic_movement;social;sensory_stim", "",
     1, 45, 1, 20, "indoor", "מוסיקה"),
    ("קבוצת שיחה", "Conversation Group", "social", "discussion",
     "social;group_activity;structured_routine;social_engagement", "",
     2, 60, 2, 12, "indoor", "שיחה"),
    ("בין-דורי", "Intergenerational", "social", "intergenerational",
     "intergenerational;family_inclusive;social;reminiscence", "",
     2, 60, 2, 30, "indoor", "בין-דורי"),
    ("טיול", "Outing", "social", "outing",
     "outings;social;light_exposure;daily_movement;nature_exposure", "long_no_bathroom_access",
     2, 90, 1, 10, "outdoor", "טיול"),
    ("ביקור מתנדבים", "Volunteer Visit", "social", "visit",
     "social;peer_visits;family_inclusive;peer_family", "",
     1, 60, 1, 1, "indoor", "ביקור"),
    ("שיחות וידיאו", "Video Calls", "social", "remote",
     "social;phone_calls;family_inclusive", "",
     2, 30, 1, 1, "indoor", "וידיאו"),
    ("מיינדפולנס", "Mindfulness", "mental", "meditation",
     "mindfulness;relaxation;breathing", "",
     2, 20, 1, 15, "indoor", "מיינדפולנס"),
    ("גינון", "Gardening", "mental", "horticulture",
     "nature_exposure;creative;sensory_stim;daily_movement;light_exposure", "",
     2, 45, 1, 8, "outdoor", "גינון"),
    ("בעלי חיים", "Animal Therapy", "mental", "animal",
     "sensory_stim;social;mindfulness;reminiscence_careful", "",
     1, 30, 1, 10, "indoor", "בעלי חיים"),
    ("חדר חושים", "Sensory Room", "mental", "sensory",
     "sensory_stim;passive_motion;mindfulness;relaxation", "",
     1, 30, 1, 5, "indoor", "חדר חושים"),
    ("פיזיותרפיה", "Physiotherapy", "physical", "therapy",
     "physiotherapy;range_of_motion;gait_training;quadriceps_strength", "",
     1, 45, 1, 1, "indoor", "פיזיו"),
    ("ריפוי בעיסוק", "Occupational Therapy", "physical", "therapy",
     "physiotherapy;complex_self_care_alone;structured_routine", "",
     1, 45, 1, 1, "indoor", "ריפוי בעיסוק"),
    ("רצפת אגן", "Pelvic Floor", "physical", "therapy",
     "pelvic_floor;timed_voiding", "",
     2, 30, 1, 1, "indoor", "רצפת אגן"),
    ("תפילה", "Religious Service", "social", "religious",
     "religious_appropriate;social;routine;reminiscence", "",
     1, 45, 1, 50, "indoor", "תפילה"),
    ("קבוצה בשפת האם", "Native Language Group", "social", "language",
     "native_language_group;cultural_familiar;social;arabic_content", "",
     2, 60, 1, 12, "indoor", "שפת אם"),
    ("מוטוריקה עדינה", "Fine Motor", "physical", "motor",
     "range_of_motion;quadriceps_strength;tactile;fine_motor", "",
     1, 20, 1, 10, "indoor", "מוטוריקה"),
    ("קפה ועיתון", "Coffee & News", "social", "discussion",
     "social;structured_routine;moderate_cognitive", "",
     1, 45, 2, 10, "indoor", "קפה ועיתון"),
    ("צפייה בסרט", "Movie", "social", "entertainment",
     "social;reminiscence;structured_routine", "",
     1, 90, 1, 30, "indoor", "סרט"),
    ("ערב שירה", "Singing Evening", "cognitive", "music",
     "music_therapy;voice_exercise;social;reminiscence", "",
     1, 60, 2, 30, "indoor", "ערב שירה"),
    ("האזנה לרדיו", "Radio Listening", "mental", "audio",
     "structured_routine;reminiscence", "",
     1, 30, 1, 1, "indoor", "רדיו"),
    ("האזנה לספר מוקלט", "Audiobook", "cognitive", "audio",
     "moderate_cognitive;mindfulness", "",
     1, 30, 1, 1, "indoor", "ספר מוקלט"),
    ("דמקה ושחמט", "Checkers & Chess", "cognitive", "games",
     "complex_cognitive;moderate_cognitive;social", "complex_instructions",
     3, 45, 2, 4, "indoor", "משחקי לוח"),
    ("שש בש (בקגמון)", "Backgammon", "cognitive", "games",
     "moderate_cognitive;social;reminiscence", "",
     2, 45, 2, 2, "indoor", "שש בש"),
    ("ברידג'", "Bridge", "cognitive", "games",
     "complex_cognitive;social", "complex_instructions",
     3, 90, 4, 4, "indoor", "ברידג'"),
    ("רמיקוב", "Rummikub", "cognitive", "games",
     "moderate_cognitive;social", "",
     2, 60, 2, 4, "indoor", "רמיקוב"),
    ("יוגה לדיירים מתחילים", "Beginner Senior Yoga", "physical", "mind_body",
     "flexibility;breathing;mindfulness", "",
     1, 30, 1, 12, "indoor", "יוגה למתחילים"),
    ("התעמלות בוקר קלה", "Light Morning Exercise", "physical", "aerobic",
     "aerobic_low;range_of_motion;daily_movement", "",
     1, 20, 1, 20, "indoor", "בוקר"),
    ("קבוצת אבל", "Grief Group", "mental", "support",
     "grief_group;social;validation", "high_pressure_competitive",
     3, 75, 4, 10, "indoor", "אבל"),
    ("דיון בחדשות", "News Discussion", "cognitive", "discussion",
     "social;moderate_cognitive;structured_routine", "trigger_topics",
     2, 45, 2, 10, "indoor", "חדשות"),
    ("טיול בגינה", "Garden Walk", "physical", "outdoor",
     "nature_exposure;light_exposure;daily_movement;aerobic_low", "",
     2, 30, 1, 10, "outdoor", "הליכה בגינה"),
    ("ישיבה במרפסת", "Porch Sitting", "mental", "outdoor",
     "light_exposure;nature_exposure;relaxation", "",
     1, 30, 1, 5, "outdoor", "מרפסת"),
    ("האזנה לעבר", "Listening to Heritage", "cognitive", "memory",
     "reminiscence;sensory_stim;social", "trigger_topics",
     1, 45, 1, 10, "indoor", "מורשת"),
    ("יוגה צחוק", "Laughter Yoga", "physical", "mind_body",
     "breathing;social;relaxation;mindfulness", "",
     1, 30, 2, 15, "indoor", "יוגה צחוק"),
    ("טבילה במים חמים", "Warm Water Soak", "physical", "therapy",
     "relaxation;range_of_motion;flexibility", "",
     2, 30, 1, 5, "indoor", "מים חמים"),
    ("עיסוי ידיים", "Hand Massage", "mental", "therapy",
     "relaxation;sensory_stim;range_of_motion", "",
     1, 20, 1, 1, "indoor", "עיסוי"),
    ("טיפול ריחני", "Aromatherapy", "mental", "sensory",
     "sensory_stim;relaxation;mindfulness", "",
     1, 20, 1, 10, "indoor", "ארומתרפיה"),
    ("טיפול במוסיקה קלאסית", "Classical Music Therapy", "cognitive", "music",
     "music_therapy;sensory_stim;mindfulness", "",
     1, 30, 1, 15, "indoor", "מוסיקה קלאסית"),
    ("יצירה בחומרי טבע", "Natural Crafts", "cognitive", "creative",
     "creative;sensory_stim;art_therapy", "",
     1, 45, 1, 8, "indoor", "יצירה"),
    ("דקלום שירה", "Poetry Recitation", "cognitive", "literature",
     "reminiscence;voice_exercise;moderate_cognitive;social", "",
     2, 45, 2, 15, "indoor", "שירה"),
    ("שיעור עברית", "Hebrew Class", "cognitive", "language",
     "language_learning;moderate_cognitive;social", "complex_instructions",
     3, 60, 2, 10, "indoor", "עברית"),
    ("צפייה בתחרות ספורט", "Watch Sports", "social", "entertainment",
     "social;reminiscence", "",
     1, 90, 1, 30, "indoor", "ספורט בטלוויזיה"),
    ("שיעור בישול", "Cooking Class", "physical", "skill",
     "structured_routine;fine_motor;social;sensory_stim", "",
     2, 60, 2, 8, "indoor", "בישול"),
    ("מאפים לחג", "Holiday Baking", "social", "skill",
     "structured_routine;creative;social;reminiscence", "",
     2, 90, 2, 8, "indoor", "אפייה"),
    ("חידון", "Quiz", "cognitive", "games",
     "moderate_cognitive;social;structured_routine", "",
     2, 45, 2, 15, "indoor", "חידון"),
    ("חידון ידע כללי", "Trivia", "cognitive", "games",
     "moderate_cognitive;social", "",
     2, 45, 2, 20, "indoor", "טריוויה"),
    ("האזנה לקריאת ספר", "Story Reading", "mental", "audio",
     "reminiscence;mindfulness;social", "",
     1, 30, 1, 15, "indoor", "סיפור"),
    ("ערב צפייה בסרטים ישנים", "Classic Films Evening", "social", "entertainment",
     "social;reminiscence;structured_routine", "",
     1, 120, 2, 30, "indoor", "סרטים ישנים"),
    ("שיחת קונדיטוריה", "Cafe Chat", "social", "discussion",
     "social;structured_routine", "",
     1, 60, 2, 8, "indoor", "קונדיטוריה"),
]


ACT_DURATION_MULT = [0.6, 0.8, 1.0, 1.2, 1.5]
ACT_MODIFIERS = [
    ("בוקר", "Morning"), ("צהריים", "Noon"),
    ("אחר הצהריים", "Afternoon"), ("ערב", "Evening"),
    ("קצרה", "Short"), ("מורחבת", "Extended"),
    ("יחידנית", "Individual"), ("קבוצתית", "Group"),
    ("מודרכת", "Guided"), ("חופשית", "Open"),
    ("מתחילים", "Beginners"), ("מתקדמים", "Advanced"),
    ("בליווי משפחה", "With Family"), ("מסורתית", "Traditional"),
    ("מודרנית", "Modern"), ("בעברית", "In Hebrew"),
    ("ברוסית", "In Russian"), ("בערבית", "In Arabic"),
    ("חיצונית", "Outdoor"), ("פנימית", "Indoor"),
]


def expand_activities(core: list) -> list:
    out = list(core)
    counter = 100
    for base in ACTIVITY_BASES:
        (b_he, b_en, cat, subcat, strengthens, contras,
         min_cap, dur, gmin, gmax, loc, desc) = base
        for mod_he, mod_en in ACT_MODIFIERS:
            for mult in ACT_DURATION_MULT:
                code = f"ACT{counter:03d}"
                counter += 1
                new_dur = max(10, int(dur * mult))
                out.append((
                    code,
                    f"{b_he} - {mod_he}",
                    f"{b_en} - {mod_en}",
                    cat,
                    subcat,
                    strengthens,
                    contras,
                    min_cap,
                    new_dur,
                    gmin,
                    gmax,
                    loc,
                    desc,
                ))
                if len(out) >= 1000:
                    return out[:1000]
    return out[:1000]


# ============================================================
# DEDICATED PHYSICAL-ACTIVITY EXPANSION
# ============================================================
# The app schedules physical activity heavily, so the physical-category pool is
# grown to a large target on its own. A wide spread of min_capability levels
# (many 1's and 2's) keeps options available even for frail residents. All tags
# come from the optimizer's needs vocabulary so these activities get matched and
# scheduled.
#   (he, en, subcat, strengthens, min_cap, dur, gmin, gmax, location)
PHYS_BASES = [
    ("הליכה נורדית", "Nordic Walking", "aerobic",
     "aerobic_low;gait_training;daily_movement;balance;light_exposure", 3, 30, 1, 10, "outdoor"),
    ("הליכה על הליכון", "Treadmill Walking", "aerobic",
     "aerobic_low;gait_training;daily_movement", 3, 20, 1, 1, "indoor"),
    ("אופניים נייחים", "Stationary Cycling", "aerobic",
     "aerobic_low;quadriceps_strength;daily_movement", 2, 20, 1, 6, "indoor"),
    ("התעמלות אירובית בישיבה", "Seated Aerobics", "aerobic",
     "aerobic_low;range_of_motion;rhythmic_movement;daily_movement", 1, 25, 1, 20, "indoor"),
    ("ריקוד סלוני", "Ballroom Dance", "dance",
     "rhythmic_movement;balance;social;aerobic_low", 3, 40, 2, 20, "indoor"),
    ("ריקודי עם", "Folk Dance", "dance",
     "rhythmic_movement;balance;social;reminiscence;aerobic_low", 2, 40, 2, 24, "indoor"),
    ("ריקוד בישיבה", "Seated Dance", "dance",
     "rhythmic_movement;range_of_motion;social;music_therapy", 1, 30, 1, 20, "indoor"),
    ("תנועה למוזיקה", "Movement to Music", "dance",
     "rhythmic_movement;music_therapy;range_of_motion;mindfulness", 1, 30, 1, 20, "indoor"),
    ("תרגילי מתיחות", "Stretching Routine", "flexibility",
     "flexibility;range_of_motion;relaxation", 1, 20, 1, 15, "indoor"),
    ("תרגילי גמישות", "Flexibility Drills", "flexibility",
     "flexibility;range_of_motion", 1, 20, 1, 15, "indoor"),
    ("מתיחות אחרי מנוחה", "Post-rest Stretching", "flexibility",
     "flexibility;range_of_motion;daily_movement", 1, 15, 1, 12, "indoor"),
    ("אימון כוח קל", "Light Strength Training", "strength",
     "quadriceps_strength;upper_body_low;weight_bearing_low", 2, 30, 1, 10, "indoor"),
    ("אימון גומיות התנגדות", "Resistance Band Training", "strength",
     "upper_body_low;quadriceps_strength;range_of_motion", 2, 25, 1, 12, "indoor"),
    ("חיזוק שרירי ליבה", "Core Strengthening", "strength",
     "quadriceps_strength;balance;weight_bearing_low", 2, 20, 1, 10, "indoor"),
    ("חדר כושר מותאם", "Adapted Gym Circuit", "strength",
     "quadriceps_strength;upper_body_low;aerobic_low;weight_bearing_low", 3, 40, 1, 6, "indoor"),
    ("אימון פונקציונלי", "Functional Training", "strength",
     "quadriceps_strength;balance;gait_training;daily_movement", 3, 30, 1, 8, "indoor"),
    ("תרגילי כדור פיזיו", "Physio Ball Exercises", "strength",
     "balance;core;range_of_motion;quadriceps_strength", 2, 25, 1, 8, "indoor"),
    ("תרגילי שיווי משקל", "Balance Drills", "balance",
     "balance;weight_bearing_low;gait_training;flexibility", 2, 20, 1, 10, "indoor"),
    ("תרגילי קואורדינציה", "Coordination Drills", "balance",
     "balance;rhythmic_movement;range_of_motion", 2, 20, 1, 10, "indoor"),
    ("תרגול יציבה", "Posture Training", "balance",
     "balance;flexibility;range_of_motion;weight_bearing_low", 1, 20, 1, 12, "indoor"),
    ("צעידה במקום", "Marching in Place", "aerobic",
     "aerobic_low;gait_training;balance;daily_movement", 2, 15, 1, 20, "indoor"),
    ("עליית מדרגות מבוקרת", "Controlled Step Training", "aerobic",
     "gait_training;quadriceps_strength;balance", 3, 15, 1, 6, "indoor"),
    ("הליכה במים", "Aqua Walking", "aquatic",
     "water_aerobics;aerobic_low;gait_training;weight_bearing_low", 2, 30, 1, 12, "indoor"),
    ("התעמלות במים", "Water Gymnastics", "aquatic",
     "water_aerobics;swimming;range_of_motion;aerobic_low", 2, 40, 1, 15, "indoor"),
    ("יוגה על כיסא", "Chair Yoga", "mind_body",
     "flexibility;breathing;mindfulness;range_of_motion;relaxation", 1, 30, 1, 15, "indoor"),
    ("פילאטיס לגיל השלישי", "Senior Pilates", "mind_body",
     "core;flexibility;balance;range_of_motion", 2, 35, 1, 12, "indoor"),
    ("צ'י גונג", "Qi Gong", "mind_body",
     "balance;breathing;rhythmic_movement;mindfulness;relaxation", 2, 30, 1, 15, "indoor"),
    ("תרגילי נשימה סרעפתית", "Diaphragmatic Breathing", "respiratory",
     "breathing;pursed_lip;relaxation;mindfulness", 1, 15, 1, 15, "indoor"),
    ("תרגילי כף רגל וקרסול", "Foot & Ankle Exercises", "mobility",
     "range_of_motion;balance;daily_movement", 1, 15, 1, 12, "indoor"),
    ("תרגילי כתפיים", "Shoulder Mobility", "mobility",
     "range_of_motion;upper_body_low;flexibility", 1, 15, 1, 12, "indoor"),
    ("תרגילי צוואר עדינים", "Gentle Neck Exercises", "mobility",
     "range_of_motion;flexibility;relaxation", 1, 12, 1, 12, "indoor"),
    ("תרגילי ידיים ואצבעות", "Hand & Finger Exercises", "mobility",
     "fine_motor;range_of_motion;tactile", 1, 15, 1, 15, "indoor"),
    ("תרגילי גב עדינים", "Gentle Back Exercises", "mobility",
     "range_of_motion;flexibility;upper_body_low", 1, 20, 1, 12, "indoor"),
    ("הליכה מודרכת בגינה", "Guided Garden Walk", "aerobic",
     "aerobic_low;nature_exposure;light_exposure;daily_movement;gait_training", 2, 30, 1, 10, "outdoor"),
    ("הליכה ידידותית לזיכרון", "Memory-friendly Walk", "aerobic",
     "aerobic_low;gait_training;daily_movement;reminiscence", 1, 20, 1, 8, "outdoor"),
    ("משחק כדור רך בקבוצה", "Soft Ball Group Game", "games",
     "range_of_motion;coordination;social;upper_body_low", 2, 30, 2, 12, "indoor"),
    ("באולינג מקורה", "Indoor Bowling", "games",
     "coordination;balance;social;upper_body_low", 2, 30, 2, 10, "indoor"),
    ("פטאנק", "Petanque", "games",
     "coordination;balance;social;daily_movement", 2, 40, 2, 8, "outdoor"),
    ("יוגה צחוק קבוצתית", "Group Laughter Yoga", "mind_body",
     "breathing;social;relaxation;mindfulness", 1, 30, 2, 15, "indoor"),
    ("התעמלות בוקר מרץ", "Energizing Morning Gymnastics", "aerobic",
     "aerobic_low;range_of_motion;daily_movement;rhythmic_movement", 2, 25, 1, 20, "indoor"),
    ("אימון סיבולת לב-ריאה קל", "Light Cardio Endurance", "aerobic",
     "aerobic_low;breathing;daily_movement", 3, 25, 1, 10, "indoor"),
    ("הליכת סקנדינביה בגינה", "Scandinavian Garden Walk", "aerobic",
     "aerobic_low;gait_training;balance;nature_exposure", 3, 30, 1, 10, "outdoor"),
    ("תרגול הליכה עם הליכון", "Walker Gait Practice", "mobility",
     "gait_training;balance;weight_bearing_low", 1, 20, 1, 4, "indoor"),
    ("תרגילי העברת משקל", "Weight-shift Exercises", "balance",
     "balance;weight_bearing_low;gait_training", 1, 20, 1, 10, "indoor"),
]

PHYS_MODIFIERS = [
    ("בוקר", "Morning"), ("אחר הצהריים", "Afternoon"),
    ("קצרה", "Short"), ("מורחבת", "Extended"),
    ("בישיבה", "Seated"), ("בעמידה", "Standing"),
    ("מתחילים", "Beginners"), ("מתקדמים", "Advanced"),
    ("קבוצתית", "Group"), ("יחידנית", "Individual"),
    ("מודרכת", "Guided"), ("עדינה", "Gentle"),
    ("עם גומיות", "With Bands"), ("עם כדור", "With Ball"),
    ("למוזיקה", "To Music"), ("מרץ", "Energizing"),
]

PHYS_DURATION_MULT = [0.7, 1.0, 1.3]


def ensure_physical_activities(activities: list, target: int = 2000) -> list:
    """Append physical-category activities until the pool holds `target` of them.

    Existing rows are preserved; new rows use deterministic PHYxxxx codes so
    re-seeding is stable. Rows match the 13-column activity schema:
    (code, he, en, category, subcat, strengthens, contras, min_cap, dur,
     gmin, gmax, location, desc).
    """
    out = list(activities)
    phys_count = sum(1 for r in out if len(r) > 3 and r[3] == "physical")
    counter = 1
    for base in PHYS_BASES:
        b_he, b_en, subcat, strengthens, min_cap, dur, gmin, gmax, loc = base
        for mod_he, mod_en in PHYS_MODIFIERS:
            for mult in PHYS_DURATION_MULT:
                if phys_count >= target:
                    return out
                code = f"PHY{counter:04d}"
                counter += 1
                new_dur = max(10, int(dur * mult))
                out.append((
                    code,
                    f"{b_he} - {mod_he}",
                    f"{b_en} - {mod_en}",
                    "physical",
                    subcat,
                    strengthens,
                    "",
                    min_cap,
                    new_dur,
                    gmin,
                    gmax,
                    loc,
                    b_he,
                ))
                phys_count += 1
    return out


# ============================================================
# EXERCISE EXPANSION
# ============================================================
EXERCISE_BASES = [
    # (he, en, ru, type, target_muscles, target_systems, strengthens, contras,
    #  intensity, min_cap, duration, reps, position, equipment, desc)
    ("סקווט בכיסא", "Chair Squats", "Приседания со стулом",
     "strength", "quadriceps;glutes;hamstrings", "musculoskeletal",
     "quadriceps_strength;weight_bearing_low;balance", "deep_squat",
     2, 3, 5, "3×10", "standing", "chair", "סקווט קל"),
    ("הרמת רגל בישיבה", "Seated Leg Raises", "Подъём ноги сидя",
     "strength", "quadriceps;hip_flexors", "musculoskeletal",
     "quadriceps_strength;range_of_motion", "",
     1, 1, 8, "2×10", "sitting", "chair", "הרמת רגל"),
    ("שכיבות סמיכה לקיר", "Wall Push-ups", "Отжимания от стены",
     "strength", "chest;triceps;shoulders;core", "musculoskeletal",
     "upper_body_low;range_of_motion", "",
     2, 2, 5, "3×10", "standing", "wall", "מול קיר"),
    ("כפיפת מרפק", "Bicep Curls", "Сгибания на бицепс",
     "strength", "biceps;forearms", "musculoskeletal",
     "upper_body_low", "heavy_lifting",
     2, 2, 8, "2×12", "sitting", "light_weights", "זרועות"),
    ("משיכת גומייה", "Band Rows", "Тяга резинкой",
     "strength", "back;biceps;rhomboids", "musculoskeletal",
     "upper_body_low;range_of_motion", "",
     2, 2, 8, "2×12", "sitting", "band", "גב"),
    ("כפיפת ברך בישיבה", "Seated Knee Extension", "Разгибание колена сидя",
     "strength", "quadriceps", "musculoskeletal",
     "quadriceps_strength", "",
     1, 1, 6, "2×10", "sitting", "chair", "ברך"),
    ("עליה על שוקיים", "Calf Raises", "Подъём на носки",
     "strength", "calves;ankles", "musculoskeletal",
     "balance;weight_bearing_low", "high_balance_demand",
     2, 3, 5, "3×15", "standing", "chair", "שוקיים"),
    ("כווץ בטן בישיבה", "Seated Ab Contractions", "Подтягивание живота сидя",
     "strength", "core;abdominals", "musculoskeletal",
     "range_of_motion;balance", "",
     1, 1, 5, "10×", "sitting", "chair", "בטן"),
    ("סיבוב כתפיים", "Shoulder Rolls", "Круговые движения плечами",
     "flexibility", "shoulders;upper_back", "musculoskeletal",
     "range_of_motion;flexibility;upper_body_low", "",
     1, 1, 4, "10+10", "sitting", "none", "כתפיים"),
    ("הליכה מהירה", "Brisk Walk", "Быстрая ходьба",
     "aerobic", "lower_body;cardiovascular", "cardiovascular;musculoskeletal",
     "aerobic_low;daily_movement;gait_training", "high_intensity",
     3, 3, 15, "15 דק'", "standing", "none", "הליכה"),
    ("אופניים נייחים", "Stationary Bike", "Велотренажёр",
     "aerobic", "quadriceps;cardiovascular", "cardiovascular;musculoskeletal",
     "aerobic_low;quadriceps_strength;daily_movement", "high_intensity",
     3, 3, 15, "15 דק' עומס נמוך", "sitting", "stationary_bike", "אופניים"),
    ("צעדים לצדדים", "Side Steps", "Шаги в сторону",
     "aerobic", "hip_abductors;cardiovascular;balance", "cardiovascular;musculoskeletal",
     "balance;aerobic_low;gait_training", "high_balance_demand",
     2, 3, 5, "5 דק'", "standing", "chair", "צדדים"),
    ("אירובי זרועות", "Arm Aerobics", "Аэробика руками",
     "aerobic", "shoulders;arms;cardiovascular", "cardiovascular",
     "aerobic_low;upper_body_low;rhythmic_movement", "",
     1, 1, 10, "10 דק'", "sitting", "none", "זרועות"),
    ("הליכון", "Treadmill", "Беговая дорожка",
     "aerobic", "lower_body;cardiovascular", "cardiovascular;musculoskeletal",
     "aerobic_low;gait_training;daily_movement", "high_intensity",
     3, 3, 15, "15 דק' איטי", "standing", "treadmill", "הליכון"),
    ("אירובי במים", "Water Aerobics", "Аква-аэробика",
     "aerobic", "full_body;cardiovascular", "cardiovascular;musculoskeletal",
     "swimming;water_aerobics;quadriceps_strength;range_of_motion;aerobic_low", "",
     2, 3, 20, "20 דק'", "pool", "pool", "מים"),
    ("ריקוד איטי", "Slow Dancing", "Медленные танцы",
     "aerobic", "lower_body;cardiovascular;coordination", "cardiovascular;neuro",
     "aerobic_low;rhythmic_movement;balance;social", "high_balance_demand",
     2, 2, 10, "10 דק'", "standing", "none", "ריקוד"),
    ("אופני יד", "Arm Ergometer", "Велоэргометр для рук",
     "aerobic", "arms;shoulders;cardiovascular", "cardiovascular;musculoskeletal",
     "aerobic_low;upper_body_low", "",
     2, 2, 12, "12 דק'", "sitting", "arm_ergometer", "אופני יד"),
    ("הליכת עקב-בוהן", "Heel-Toe Walk", "Ходьба пятка-носок",
     "balance", "core;ankles;balance", "neuro;musculoskeletal",
     "balance;gait_training", "high_balance_demand",
     2, 3, 5, "10 צעדים", "standing", "wall", "עקב-בוהן"),
    ("מתיחת אחורי ירך", "Hamstring Stretch", "Растяжка задней поверхности бедра",
     "flexibility", "hamstrings;lower_back", "musculoskeletal",
     "flexibility;range_of_motion;relaxation", "",
     1, 1, 5, "30 שניות×3", "sitting", "chair", "מתיחה"),
    ("נשימה דיאפרגמטית", "Diaphragmatic Breathing", "Диафрагмальное дыхание",
     "breathing", "diaphragm;respiratory", "respiratory",
     "breathing;pursed_lip;relaxation;mindfulness", "",
     1, 1, 10, "10 דק'", "sitting", "none", "נשימה"),
    ("פלאנק מודרך", "Modified Plank", "Модифицированная планка",
     "strength", "core;abs;back", "musculoskeletal",
     "range_of_motion;balance", "",
     3, 3, 5, "20 שניות×3", "lying", "mat", "פלאנק"),
    ("גשר ירכיים", "Glute Bridge", "Ягодичный мост",
     "strength", "glutes;hamstrings;core", "musculoskeletal",
     "weight_bearing_low;quadriceps_strength;range_of_motion", "",
     2, 2, 8, "2×10", "lying", "mat", "גשר"),
    ("פתיחת רגליים בישיבה", "Seated Hip Abduction", "Отведение бедра сидя",
     "strength", "hip_abductors;outer_thighs", "musculoskeletal",
     "balance;range_of_motion", "",
     1, 1, 6, "2×10", "sitting", "band", "פתיחה"),
    ("סגירת רגליים בישיבה", "Seated Hip Adduction", "Сведение бедра сидя",
     "strength", "hip_adductors;inner_thighs", "musculoskeletal",
     "range_of_motion;quadriceps_strength", "",
     1, 1, 6, "2×10", "sitting", "ball", "סגירה"),
    ("הליכה במקום", "Marching in Place", "Шаги на месте",
     "aerobic", "lower_body;cardiovascular", "cardiovascular;musculoskeletal",
     "aerobic_low;gait_training;daily_movement", "",
     1, 2, 5, "5 דק'", "standing", "chair", "מקום"),
    ("מתיחת חזה", "Chest Stretch", "Растяжка груди",
     "flexibility", "chest;shoulders", "musculoskeletal",
     "flexibility;range_of_motion;upper_body_low", "",
     1, 1, 5, "30 שניות×3", "standing", "none", "מתיחת חזה"),
    ("מתיחת צוואר", "Neck Stretch", "Растяжка шеи",
     "flexibility", "neck;upper_back", "musculoskeletal",
     "flexibility;range_of_motion;relaxation", "",
     1, 1, 5, "30 שניות×3", "sitting", "none", "צוואר"),
    ("סיבוב מותניים", "Trunk Rotation", "Скручивание корпуса",
     "flexibility", "core;obliques", "musculoskeletal",
     "range_of_motion;flexibility;balance", "",
     1, 1, 5, "10+10", "sitting", "none", "מותניים"),
    ("עמידה על רגל אחת", "Single Leg Stand", "Стойка на одной ноге",
     "balance", "core;ankles;balance", "neuro;musculoskeletal",
     "balance;gait_training", "high_balance_demand",
     2, 3, 5, "30 שניות×4", "standing", "wall", "עמידה"),
    ("נשימה 4-7-8", "4-7-8 Breathing", "Дыхание 4-7-8",
     "breathing", "diaphragm;respiratory", "respiratory",
     "breathing;mindfulness;relaxation", "",
     1, 1, 10, "5 מחזורים", "sitting", "none", "4-7-8"),
    ("שינוי תנוחה", "Postural Change", "Изменение позы",
     "balance", "core;balance", "neuro;musculoskeletal",
     "balance;range_of_motion", "sudden_position_change",
     1, 2, 5, "5 חזרות", "standing", "chair", "תנוחה"),
    ("מתיחת זרוע מעל הראש", "Overhead Arm Stretch", "Растяжка рук над головой",
     "flexibility", "shoulders;triceps", "musculoskeletal",
     "flexibility;range_of_motion;upper_body_low", "",
     1, 1, 4, "30 שניות×3", "standing", "none", "מעל ראש"),
    ("רוקדים מקומיים", "Local Dancing", "Местные танцы",
     "aerobic", "full_body;cardiovascular", "cardiovascular",
     "aerobic_low;rhythmic_movement;social", "",
     2, 2, 15, "15 דק'", "standing", "none", "ריקודים"),
    ("מתיחת ירך", "Hip Stretch", "Растяжка бедра",
     "flexibility", "hip_flexors;quadriceps", "musculoskeletal",
     "flexibility;range_of_motion", "",
     1, 1, 5, "30 שניות×3", "lying", "mat", "ירך"),
    ("ארבע נקודות", "Quadruped", "Четвероножка",
     "strength", "core;back;balance", "musculoskeletal",
     "range_of_motion;balance", "",
     2, 3, 5, "10×", "kneeling", "mat", "ארבע"),
    ("מתיחת קיר", "Wall Stretch", "Растяжка у стены",
     "flexibility", "calves;hamstrings", "musculoskeletal",
     "flexibility;range_of_motion", "",
     1, 2, 5, "30 שניות×3", "standing", "wall", "קיר"),
    ("הליכה לאחור", "Backward Walking", "Ходьба назад",
     "balance", "lower_body;balance", "neuro;musculoskeletal",
     "balance;gait_training;quadriceps_strength", "high_balance_demand",
     2, 3, 5, "5 דק' ליד מעקה", "standing", "wall", "לאחור"),
    ("מתיחת גב", "Back Stretch", "Растяжка спины",
     "flexibility", "back;core", "musculoskeletal",
     "flexibility;range_of_motion;relaxation", "",
     1, 1, 5, "30 שניות×3", "sitting", "chair", "גב"),
    ("מתיחת שורש כף יד", "Wrist Stretch", "Растяжка запястий",
     "flexibility", "wrists;forearms", "musculoskeletal",
     "fine_motor;flexibility;range_of_motion", "",
     1, 1, 3, "30 שניות×3", "sitting", "none", "שורש"),
    ("פתיחת כתפיים", "Shoulder Opener", "Открытие плеч",
     "flexibility", "shoulders;chest", "musculoskeletal",
     "flexibility;upper_body_low;range_of_motion", "",
     1, 1, 5, "30 שניות×3", "standing", "none", "כתפיים פתוחות"),
    ("מתיחת קרסול", "Ankle Circles", "Круги стопами",
     "flexibility", "ankles", "musculoskeletal",
     "flexibility;range_of_motion;balance", "",
     1, 1, 3, "10+10", "sitting", "none", "קרסול"),
    ("מתיחת אצבעות", "Finger Stretch", "Растяжка пальцев",
     "flexibility", "fingers;hands", "musculoskeletal",
     "fine_motor;flexibility;range_of_motion", "",
     1, 1, 3, "10×", "sitting", "none", "אצבעות"),
    ("הליכה מאחור לפנים", "Walking Forward-Back", "Ходьба вперёд-назад",
     "balance", "lower_body;balance", "neuro;musculoskeletal",
     "balance;gait_training", "high_balance_demand",
     2, 3, 5, "10 צעדים×3", "standing", "wall", "קדימה-אחורה"),
    ("נשימה דרך האף", "Nasal Breathing", "Дыхание через нос",
     "breathing", "diaphragm;respiratory", "respiratory",
     "breathing;mindfulness", "",
     1, 1, 5, "5 דק'", "sitting", "none", "נשימת אף"),
    ("נשימה לסירוגין", "Alternate Nostril", "Дыхание попеременно",
     "breathing", "diaphragm;respiratory", "respiratory;neuro",
     "breathing;mindfulness;relaxation", "",
     2, 2, 10, "10 דק'", "sitting", "none", "לסירוגין"),
    ("פילאטיס בכיסא", "Chair Pilates", "Пилатес сидя",
     "strength", "core;back;abs", "musculoskeletal",
     "range_of_motion;flexibility;balance", "",
     2, 2, 20, "20 דק'", "sitting", "chair", "פילאטיס"),
    ("ארג'יקיו פנים", "Facial Qigong", "Цигун лица",
     "flexibility", "face;neck", "neuro",
     "relaxation;mindfulness", "",
     1, 1, 10, "10 דק'", "sitting", "none", "פנים"),
    ("טאי צ'י לחימה", "Tai Chi Forms", "Тай-чи формы",
     "balance", "full_body;balance", "neuro;musculoskeletal",
     "balance;rhythmic_movement;flexibility;mindfulness", "high_balance_demand",
     2, 2, 30, "30 דק'", "standing", "none", "צורות"),
    ("מתיחות סטרץ' פעיל", "Active Stretching", "Активное растягивание",
     "flexibility", "full_body", "musculoskeletal",
     "flexibility;range_of_motion;balance", "",
     2, 2, 20, "20 דק'", "standing", "none", "סטרץ'"),
    ("חיזוק שורש כף יד", "Wrist Strengthening", "Укрепление запястий",
     "strength", "wrists;forearms", "musculoskeletal",
     "fine_motor;range_of_motion", "",
     2, 2, 5, "2×10", "sitting", "light_weights", "שורש"),
]


EX_INTENSITY_VARIANTS = [
    ("מאוד קל", "Very Light"), ("קל", "Light"),
    ("מתון", "Moderate"), ("מאמץ בינוני", "Moderate Effort"),
    ("מתחילים", "Beginner"), ("בינוני", "Intermediate"),
    ("מתקדם", "Advanced"), ("מותאם בית אבות", "Nursing-Home Adapted"),
    ("בקבוצה", "Group"), ("פרטני", "Individual"),
    ("מודרך", "Guided"), ("עצמאי", "Independent"),
    ("עם משקל קל", "Light Weight"), ("ללא משקל", "Bodyweight"),
    ("איטי", "Slow"), ("בקצב", "Rhythmic"),
    ("דגש על נשימה", "Breath-focused"), ("דגש על איזון", "Balance-focused"),
    ("רגיש לכאב", "Pain-Sensitive"), ("שיקומי", "Rehabilitative"),
]


def expand_exercises(core: list) -> list:
    out = list(core)
    counter = 100
    for base in EXERCISE_BASES:
        (b_he, b_en, b_ru, typ, muscles, systems, strengthens, contras,
         intensity, min_cap, dur, reps, position, equip, desc) = base
        for mod_he, mod_en in EX_INTENSITY_VARIANTS:
            code = f"EX{counter:03d}"
            counter += 1
            out.append((
                code,
                f"{b_he} - {mod_he}",
                f"{b_en} - {mod_en}",
                f"{b_ru} - {mod_en}",
                typ, muscles, systems,
                strengthens, contras,
                intensity, min_cap, dur, reps, position, equip, desc,
            ))
            if len(out) >= 1000:
                return out[:1000]
    return out[:1000]
