"""
ElderCare - Knowledge Bank Seeder
Generates Excel seed files for: diseases, medications, conditions, activities.

Each row carries:
- bilingual names (he / en)
- limitations / contraindications it creates
- what it needs strengthening for

Run once to (re)create the .xlsx files. Edit Excel after to expand the banks.
"""

from pathlib import Path
import sys
import pandas as pd

# Allow running both as `python knowledge_banks/seed_data.py` (direct) and
# as `python -m knowledge_banks.seed_data` (module). When direct, the
# parent directory is not on sys.path — add it so `knowledge_banks` package
# can be imported.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from knowledge_banks.expansions import (  # noqa: E402
    expand_diseases, expand_medications,
    expand_activities, expand_exercises,
    ensure_physical_activities,
)

OUT_DIR = Path(__file__).parent


# --- DIMENSION TAGS ---------------------------------------------------------
# Every "limitation" and every "strengthens" is tagged with a dimension so the
# optimizer can match needs to activities.
DIMS = [
    "medical", "medication", "nursing", "cognitive",
    "social", "family", "mental", "demographic", "motor",
]


# --- 1. DISEASES ------------------------------------------------------------
diseases = [
    # code, name_he, name_en, category, limitations, needs, description_he
    ("DIS001", "סוכרת סוג 2", "Type 2 Diabetes", "metabolic",
     "high_intensity_long_fast;sugar_rich_food",
     "aerobic_low;balanced_diet;daily_movement",
     "מחלה מטבולית - דורש פעילות מתונה קבועה ותזונה מאוזנת"),
    ("DIS002", "יתר לחץ דם", "Hypertension", "cardiovascular",
     "high_intensity;heavy_lifting;sudden_position_change",
     "aerobic_low;breathing;relaxation",
     "לחץ דם גבוה - הימנע ממאמץ קיצוני, חזק נשימה והרפיה"),
    ("DIS003", "אוסטאופורוזיס", "Osteoporosis", "musculoskeletal",
     "high_impact;jumping;contact_sport;falls_risk",
     "weight_bearing_low;balance;flexibility",
     "דלדול עצמות - פעילות נושאת משקל קלה, איזון, גמישות"),
    ("DIS004", "אוסטאוארתריטיס ברך", "Knee Osteoarthritis", "musculoskeletal",
     "running;jumping;deep_squat;stairs_high",
     "swimming;water_aerobics;quadriceps_strength;range_of_motion",
     "שחיקת סחוס בברך - מים, חיזוק שריר ארבע ראשי, טווח תנועה"),
    ("DIS005", "מחלת אלצהיימר קלה", "Mild Alzheimer's", "cognitive_decline",
     "complex_instructions;new_environment_alone;unsupervised",
     "memory_games;routine;reminiscence;social_engagement",
     "אלצהיימר קל - שגרה קבועה, גירוי קוגניטיבי, מעורבות חברתית"),
    ("DIS006", "דמנציה בינונית", "Moderate Dementia", "cognitive_decline",
     "complex_instructions;new_environment_alone;multi_step_tasks;unsupervised",
     "simple_routine;music_therapy;sensory_stim;reminiscence",
     "דמנציה בינונית - גרייה חושית, מוסיקה, סיפורי עבר, שגרה פשוטה"),
    ("DIS007", "פרקינסון", "Parkinson's Disease", "neurological",
     "high_balance_demand;fast_changes;crowded_space",
     "balance;rhythmic_movement;gait_training;voice_exercise;flexibility",
     "פרקינסון - אימון איזון, תנועה קצבית, גמישות, אימון קול"),
    ("DIS008", "אי ספיקת לב כרונית", "Chronic Heart Failure", "cardiovascular",
     "high_intensity;long_duration;hot_environment",
     "aerobic_very_low;breathing;monitored",
     "אי ספיקת לב - פעילות מתונה מאוד תחת השגחה, נשימה"),
    ("DIS009", "COPD", "COPD", "respiratory",
     "high_intensity;cold_air;dusty_environment",
     "breathing;pursed_lip;upper_body_low;walk_short",
     "מחלת ריאות חסימתית - אימון נשימה, פעילות קצרה ומתונה"),
    ("DIS010", "דיכאון קליני", "Clinical Depression", "mental",
     "isolation;over_stimulation",
     "social;light_exposure;aerobic_low;structured_routine;creative",
     "דיכאון - חיבור חברתי, חשיפה לאור, פעילות יוצרת, שגרה"),
    ("DIS011", "חרדה כללית", "Generalized Anxiety", "mental",
     "loud_crowds;competitive;time_pressure",
     "breathing;mindfulness;yoga;nature_exposure;art_therapy",
     "חרדה כללית - נשימה, מיינדפולנס, יוגה, אומנות"),
    ("DIS012", "ירידה בשמיעה", "Hearing Loss", "sensory",
     "audio_only_activities;noisy_environment",
     "visual_cues;small_group;subtitles;sign_supported",
     "ליקוי שמיעה - העדף פעילות חזותית, קבוצות קטנות"),
    ("DIS013", "ליקוי ראייה", "Visual Impairment", "sensory",
     "visual_only_activities;poor_lighting;reading_small",
     "audio_based;tactile;large_print;guided_walks",
     "ליקוי ראייה - שמע, מישוש, הדפסה מוגדלת"),
    ("DIS014", "סטטוס פוסט שבץ", "Post-Stroke", "neurological",
     "high_intensity;complex_motor;unsupervised",
     "physiotherapy;speech_therapy;range_of_motion;mirror_therapy",
     "אחרי שבץ - פיזיותרפיה, ריפוי בדיבור, טווחי תנועה"),
    ("DIS015", "אגירת שתן/אינקונטיננציה", "Incontinence", "urological",
     "long_no_bathroom_access",
     "pelvic_floor;timed_voiding;short_sessions",
     "בריחת שתן - הימנע ממפגשים ארוכים ללא שירותים"),
]
diseases = expand_diseases(diseases)
pd.DataFrame(diseases, columns=[
    "code", "name_he", "name_en", "category",
    "limitations", "needs_strengthening", "description_he",
]).to_excel(OUT_DIR / "diseases.xlsx", index=False)


# --- 2. MEDICATIONS ---------------------------------------------------------
# Each medication carries activity contraindications (movements/situations to
# avoid while on the drug) AND any rehabilitative needs the drug profile
# suggests reinforcing through activity.
medications = [
    # code, name_he, name_en, drug_class, side_effects, activity_contras,
    # needs_strengthening, description
    ("MED001", "מטפורמין", "Metformin", "antidiabetic",
     "gi_upset;mild_fatigue",
     "high_intensity_long_fast",
     "aerobic_low;daily_movement",
     "תרופה לסוכרת - שמור על מים ופעילות מתונה"),
    ("MED002", "וורפרין", "Warfarin", "anticoagulant",
     "bleeding_risk;bruising",
     "contact_sport;high_fall_risk;sharp_tools",
     "balance;gait_training",
     "מדלל דם - הימנע מספורט עם סיכון נפילה או חתכים"),
    ("MED003", "אספירין מינון נמוך", "Low-dose Aspirin", "antiplatelet",
     "bleeding_risk_mild",
     "contact_sport",
     "aerobic_low;daily_movement;balanced_diet",
     "אספירין - הימנע מספורט מגע, פעילות אירובית קלה לבריאות הלב"),
    ("MED004", "סטטין", "Statin", "lipid_lowering",
     "muscle_pain;fatigue",
     "extreme_endurance",
     "aerobic_low",
     "סטטין - שים לב לכאבי שרירים, הימנע ממאמץ סבולת קיצוני"),
    ("MED005", "אנלפריל/לוסארטן", "ACE-i / ARB", "antihypertensive",
     "dizziness_on_standing;dry_cough",
     "sudden_position_change",
     "breathing;relaxation",
     "תרופה ללחץ דם - הימנע משינוי תנוחה פתאומי"),
    ("MED006", "בטא בלוקר", "Beta Blocker", "cardiac",
     "lower_max_hr;fatigue",
     "high_intensity",
     "aerobic_low",
     "בטא בלוקר - הגבל עצימות, התחשב בקצב לב נמוך"),
    ("MED007", "דיגוקסין", "Digoxin", "cardiac_glycoside",
     "nausea;visual_disturbance",
     "high_intensity",
     "aerobic_low",
     "דיגוקסין - שים לב לסחרחורות וראייה"),
    ("MED008", "פוורסמיד", "Furosemide", "diuretic",
     "dehydration;urinary_frequency",
     "long_no_bathroom_access;hot_environment",
     "aerobic_very_low;balanced_diet;hydration;timed_voiding",
     "משתן - יש לוודא נגישות לשירותים, מים, פעילות מתונה מאוד"),
    ("MED009", "ל-דופא", "Levodopa", "antiparkinson",
     "dyskinesia;orthostatic_drop;sleepiness",
     "high_balance_demand_when_off",
     "balance;voice_exercise;gait_training",
     "תרופה לפרקינסון - תזמן פעילות לזמן 'on'"),
    ("MED010", "דונפזיל", "Donepezil", "cholinesterase_inhibitor",
     "gi_upset;sleep_disturbance",
     "",
     "memory_games;moderate_cognitive",
     "תרופה לאלצהיימר - מעודד פעילות קוגניטיבית"),
    ("MED011", "ממנטין", "Memantine", "nmda_antagonist",
     "dizziness;confusion",
     "high_balance_demand",
     "memory_games;sensory_stim",
     "תרופה לדמנציה - שים לב לסחרחורות"),
    ("MED012", "SSRI", "SSRI", "antidepressant",
     "gi_upset;sleep_changes",
     "",
     "social;aerobic_low;light_exposure",
     "תרופה לדיכאון - מתאם היטב עם פעילות אירובית"),
    ("MED013", "בנזודיאזפינים", "Benzodiazepines", "anxiolytic",
     "sedation;fall_risk;cognitive_blunting",
     "high_balance_demand;complex_cognitive",
     "breathing;mindfulness",
     "תרופת הרגעה - מעלה סיכון נפילה, מקהה קוגניציה"),
    ("MED014", "אופיואידים", "Opioids", "analgesic",
     "sedation;constipation;balance_impairment",
     "high_balance_demand;high_intensity",
     "balance;mindfulness;range_of_motion;hydration",
     "משככי כאב חזקים - מנמנם, מפחית איזון, חיזוק איזון ושתייה"),
    ("MED015", "אינסולין", "Insulin", "antidiabetic",
     "hypoglycemia_risk",
     "high_intensity_long_fast",
     "aerobic_low;daily_movement",
     "אינסולין - שים לב לרמת סוכר לפני ואחרי פעילות"),
]
medications = expand_medications(medications)
pd.DataFrame(medications, columns=[
    "code", "name_he", "name_en", "drug_class",
    "side_effects", "activity_contraindications",
    "needs_strengthening", "description_he",
]).to_excel(OUT_DIR / "medications.xlsx", index=False)


# --- 3. CONDITIONS (nursing / cognitive / mental / social / family / demographic) -----
conditions = [
    # code, name_he, name_en, dimension, severity, limitations, needs, description
    ("CON001", "עצמאי לחלוטין (ADL)", "Fully Independent (ADL)",
     "nursing", "none", "", "challenge_appropriate",
     "עצמאות מלאה - אתגר פעילויות מורכבות יותר"),
    ("CON002", "תלוי חלקית בהלבשה/רחצה", "Partial Dependence",
     "nursing", "mild", "complex_self_care_alone", "assistance_available;simplified",
     "תלות חלקית - פעילויות בליווי מטפל"),
    ("CON003", "תלוי מלא", "Fully Dependent",
     "nursing", "severe", "standalone_activity;outside_unaccompanied",
     "bed_chair_based;sensory_stim;passive_motion",
     "תלות מלאה - גרייה חושית במיטה/כיסא"),
    ("CON004", "MMSE 24-30 (תקין)", "MMSE 24-30 normal",
     "cognitive", "none", "", "complex_cognitive;learning_new",
     "קוגניציה תקינה"),
    ("CON005", "MMSE 19-23 (ירידה קלה)", "MMSE 19-23 mild",
     "cognitive", "mild", "very_complex_multi_step", "memory_games;moderate_cognitive",
     "ירידה קוגניטיבית קלה"),
    ("CON006", "MMSE 10-18 (בינונית)", "MMSE 10-18 moderate",
     "cognitive", "moderate", "complex_multi_step;new_environment_alone",
     "simple_routine;reminiscence;sensory",
     "ירידה קוגניטיבית בינונית"),
    ("CON007", "MMSE <10 (חמורה)", "MMSE <10 severe",
     "cognitive", "severe", "complex_instructions;unsupervised",
     "sensory_stim;music;familiar_objects",
     "ירידה קוגניטיבית חמורה"),
    ("CON008", "בודד חברתית", "Socially isolated",
     "social", "high", "", "group_activity;peer_visits;phone_calls;outings",
     "בדידות - חיבור קבוצתי, ביקורים, יציאות"),
    ("CON009", "פעיל חברתית", "Socially active",
     "social", "low", "", "maintain_social",
     "פעיל חברתית - לשמור על קשרים"),
    ("CON010", "תומך משפחתי קרוב", "Strong family support",
     "family", "high", "", "family_inclusive;intergenerational",
     "משפחה קרובה - שיתוף בני משפחה"),
    ("CON011", "ללא תמיכה משפחתית", "No family support",
     "family", "none", "", "peer_family;volunteer_visits",
     "אין משפחה - מצא תחליפי משפחה"),
    ("CON012", "אבל טרי (פחות מ-6 חודשים)", "Recent grief",
     "mental", "high", "high_pressure_competitive", "grief_group;creative_therapy;routine",
     "אבל טרי - קבוצות תמיכה, ביטוי יצירתי"),
    ("CON013", "ניצול שואה", "Holocaust survivor",
     "cultural", "trigger_sensitive", "trigger_topics;authoritarian_settings",
     "validation;survivor_community;reminiscence_careful",
     "ניצול שואה - רגיש לטריגרים, חיבור לקהילת ניצולים"),
    ("CON014", "עולה חדש", "Recent immigrant",
     "cultural", "language_barrier", "native_language_only_complex",
     "native_language_group;cultural_familiar;language_learning",
     "עולה חדש - קבוצה בשפת האם, פעילות תרבותית מוכרת"),
    ("CON015", "דובר ערבית", "Arabic speaker",
     "cultural", "language_specific", "", "arabic_content;culturally_appropriate",
     "דובר ערבית - תוכן בשפה ובהקשר תרבותי"),
    ("CON016", "דתי", "Religiously observant",
     "cultural", "values_specific", "shabbat_violation;mixed_gender_sensitive",
     "religious_appropriate;prayer_times_respected",
     "דתי - התחשב בשעות תפילה, הפרדה אם נדרש"),
    ("CON017", "נוצרי", "Christian",
     "cultural", "values_specific", "",
     "christian_appropriate",
     "נוצרי - בדוק חגי כנסיה ומסורת"),

    # ============================================================
    # 100 MENTAL HEALTH CONDITIONS (CON100-CON199)
    # depression spectrum / anxiety / PTSD / grief / OCD / bipolar /
    # psychotic / sleep / cognitive-affective / substance / personality /
    # identity / stress / combined / behavioral
    # ============================================================

    # ----- DEPRESSION SPECTRUM (15) -----
    ("CON100", "דיכאון קל", "Mild Depression", "mental", "mild",
     "isolation;over_stimulation",
     "social;light_exposure;aerobic_low;structured_routine;creative;behavioral_activation",
     "דיכאון קל - הפעלה התנהגותית עדינה, חיבור חברתי, אור"),
    ("CON101", "דיכאון בינוני", "Moderate Depression", "mental", "moderate",
     "isolation;over_stimulation;sleep_disruption",
     "social;light_exposure;aerobic_low;structured_routine;creative;music_therapy;behavioral_activation",
     "דיכאון בינוני - שגרה מובנת, מוסיקה, פעילות יוצרת"),
    ("CON102", "דיכאון חמור", "Severe Depression", "mental", "severe",
     "isolation;over_stimulation;competitive;high_pressure_competitive",
     "social;light_exposure;aerobic_very_low;structured_routine;one_on_one;gentle_movement;hope_focus",
     "דיכאון חמור - תמיכה 1-על-1, פעילות עדינה, מעקב פסיכיאטרי"),
    ("CON103", "דיכאון מג'ורי (MDD)", "Major Depressive Disorder", "mental", "moderate",
     "isolation;competitive;high_pressure_competitive",
     "social;light_exposure;aerobic_low;structured_routine;creative;behavioral_activation;family_inclusive",
     "MDD - הפעלה התנהגותית, מבנה יום, מעקב תרופתי"),
    ("CON104", "דיכאון מתמשך (דיסטימיה)", "Persistent Depressive Disorder", "mental", "chronic",
     "isolation",
     "social;structured_routine;aerobic_low;meaning_focus;creative",
     "דיסטימיה - מצב רוח נמוך מתמשך, מבנה ומשמעות"),
    ("CON105", "דיכאון עונתי", "Seasonal Affective Disorder", "mental", "seasonal",
     "isolation;darkness",
     "light_exposure;light_therapy;social;aerobic_low;outdoor_daytime",
     "SAD - חשיפה לאור בוקר, פעילות חוץ ביום"),
    ("CON106", "דיכאון עמיד לטיפול", "Treatment-Resistant Depression", "mental", "chronic",
     "isolation;competitive;high_intensity",
     "social;one_on_one;gentle_movement;art_therapy;music_therapy;hope_focus;validation",
     "דיכאון עמיד - גישות יצירתיות, תיקוף, סבלנות"),
    ("CON107", "דיכאון דו-קוטבי", "Bipolar Depression", "mental", "moderate",
     "sleep_disruption;over_stimulation",
     "structured_routine;social;light_exposure;sleep_hygiene;mindfulness",
     "דיכאון בהפרעה דו-קוטבית - יציבות שגרה, מעקב"),
    ("CON108", "דיכאון אטיפי", "Atypical Depression", "mental", "moderate",
     "isolation;evening_meals",
     "social;light_exposure;aerobic_low;structured_meals;creative",
     "דיכאון אטיפי - היפר-שינה, רגישות לדחייה, מבנה"),
    ("CON109", "דיכאון פסיכוטי", "Psychotic Depression", "mental", "severe",
     "over_stimulation;loud_crowds;trigger_topics",
     "one_on_one;structured_routine;sensory_stim;validation;soothing_voice",
     "דיכאון פסיכוטי - הזיות, הימנע מגירוי, סביבה רגועה"),
    ("CON110", "דיכאון קטטוני", "Catatonic Depression", "mental", "severe",
     "complex_instructions;sudden_changes",
     "one_on_one;passive_motion;sensory_stim;gentle_touch;music_familiar",
     "דיכאון קטטוני - חוסר תגובה, גירוי חושי עדין"),
    ("CON111", "דיכאון וסקולרי", "Vascular Depression", "mental", "moderate",
     "high_intensity;complex_instructions",
     "social;aerobic_low;structured_routine;memory_games;light_exposure",
     "דיכאון וסקולרי - שכיח בדיירים, קשור לפגיעה מוחית"),
    ("CON112", "דיכאון של גיל מאוחר", "Late-Life Depression", "mental", "moderate",
     "isolation;trigger_topics",
     "social;reminiscence;structured_routine;family_inclusive;meaning_focus;peer_visits",
     "דיכאון בגיל מבוגר - לעיתים מתחפש לתלונות גופניות"),
    ("CON113", "דיכאון תת-קליני", "Subsyndromal Depression", "mental", "mild",
     "isolation",
     "social;light_exposure;aerobic_low;structured_routine;creative",
     "דיכאון תת-קליני - תסמינים חלקיים אך משפיעים"),
    ("CON114", "דיכאון אחרי אובדן", "Bereavement-Related Depression", "mental", "moderate",
     "isolation;trigger_topics;high_pressure_competitive",
     "social;grief_group;reminiscence;validation;spiritual_support;family_inclusive",
     "דיכאון אחרי אובדן - חפיפה עם אבל"),

    # ----- ANXIETY SPECTRUM (10) -----
    ("CON115", "חרדה כללית קלה", "Mild Generalized Anxiety", "mental", "mild",
     "loud_crowds;time_pressure;over_stimulation",
     "breathing;mindfulness;yoga;nature_exposure;relaxation",
     "חרדה קלה - הרפיה, נשימה, טבע"),
    ("CON116", "חרדה כללית בינונית", "Moderate Generalized Anxiety", "mental", "moderate",
     "loud_crowds;competitive;time_pressure;over_stimulation;sudden_changes",
     "breathing;mindfulness;yoga;nature_exposure;art_therapy;relaxation;predictable_routine",
     "חרדה בינונית - מבנה, הרפיה מודרכת, אומנות"),
    ("CON117", "חרדה כללית חמורה", "Severe Generalized Anxiety", "mental", "severe",
     "loud_crowds;competitive;time_pressure;over_stimulation;sudden_changes;crowded_space",
     "breathing;mindfulness;one_on_one;sensory_stim;predictable_routine;soothing_voice",
     "חרדה חמורה - סביבה רגועה, 1-על-1"),
    ("CON118", "התקפי פאניקה", "Panic Disorder", "mental", "episodic",
     "crowded_space;loud_crowds;high_intensity",
     "breathing;mindfulness;relaxation;predictable_routine;sensory_stim",
     "פאניקה - אוורור, פעילות צפויה ובטוחה"),
    ("CON119", "חרדה חברתית", "Social Anxiety", "mental", "moderate",
     "large_groups;crowded_space;unfamiliar_people",
     "one_on_one;peer_visits;creative;breathing;gentle_movement",
     "חרדה חברתית - מפגשים קטנים ומוכרים"),
    ("CON120", "אגורפוביה", "Agoraphobia", "mental", "moderate",
     "crowded_space;outings;large_groups",
     "home_based_options;social;one_on_one;creative;relaxation",
     "אגורפוביה - חוסר נכונות לצאת מהבית"),
    ("CON121", "חרדת בריאות", "Health Anxiety", "mental", "moderate",
     "intrusive_questions;trigger_topics;medical_focus",
     "mindfulness;art_therapy;social;creative;structured_routine",
     "חרדת בריאות - הסחה ביצירה, מבנה יום"),
    ("CON122", "פוביה ספציפית", "Specific Phobia", "mental", "mild",
     "trigger_topics",
     "breathing;mindfulness;structured_routine;creative",
     "פוביה - הימנע מטריגרים, חיזוק התמודדות"),
    ("CON123", "חרדת ציפייה", "Anticipatory Anxiety", "mental", "mild",
     "time_pressure;sudden_changes",
     "predictable_routine;mindfulness;breathing;relaxation",
     "חרדת ציפייה - שגרה צפויה, מיינדפולנס"),
    ("CON124", "חרדת פרידה", "Separation Anxiety", "mental", "moderate",
     "alone_extended",
     "family_inclusive;social;peer_visits;phone_calls;pet_companionship",
     "חרדת פרידה - הימנע מבדידות ממושכת"),

    # ----- PTSD & TRAUMA (9) -----
    ("CON125", "PTSD קל", "Mild PTSD", "mental", "mild",
     "trigger_topics;loud_crowds;sudden_changes",
     "mindfulness;breathing;creative;social;nature_exposure",
     "PTSD קל - הימנע מטריגרים, סביבה צפויה"),
    ("CON126", "PTSD בינוני", "Moderate PTSD", "mental", "moderate",
     "trigger_topics;loud_crowds;sudden_changes;authoritarian_settings",
     "mindfulness;breathing;creative;one_on_one;validation;art_therapy",
     "PTSD בינוני - תיקוף, ביטוי יצירתי, סביבה בטוחה"),
    ("CON127", "PTSD חמור", "Severe PTSD", "mental", "severe",
     "trigger_topics;loud_crowds;sudden_changes;authoritarian_settings;intrusive_questions",
     "one_on_one;sensory_stim;breathing;validation;soothing_voice;predictable_routine",
     "PTSD חמור - מומחה טיפולי, סביבה צפויה ובטוחה"),
    ("CON128", "PTSD מורכב (C-PTSD)", "Complex PTSD", "mental", "chronic",
     "trigger_topics;intrusive_questions;authoritarian_settings",
     "one_on_one;validation;art_therapy;mindfulness;reminiscence_careful;peer_support",
     "PTSD מורכב - טראומה מתמשכת, צריך תיקוף ועקביות"),
    ("CON129", "תגובת דחק חריפה", "Acute Stress Reaction", "mental", "acute",
     "over_stimulation;sudden_changes;trigger_topics",
     "soothing_voice;structured_routine;social;breathing;family_inclusive",
     "תגובה לסטרס חריף - בטיחות, תמיכה, מבנה"),
    ("CON130", "הפרעת הסתגלות", "Adjustment Disorder", "mental", "acute",
     "isolation",
     "social;structured_routine;creative;family_inclusive;peer_visits",
     "הפרעת הסתגלות - תמיכה במעבר חיים"),
    ("CON131", "טראומה הקשורה לשואה", "Holocaust-Related Trauma", "mental", "chronic",
     "trigger_topics;authoritarian_settings;intrusive_questions",
     "validation;survivor_community;reminiscence_careful;art_therapy;music_familiar",
     "טראומה מהשואה - תיקוף, קהילת ניצולים, רגישות"),
    ("CON132", "טראומת מלחמה", "War-Related Trauma", "mental", "chronic",
     "trigger_topics;loud_crowds;authoritarian_settings",
     "validation;peer_support;mindfulness;art_therapy;creative",
     "טראומת מלחמה - תיקוף, קבוצת ותיקים, ביטוי"),
    ("CON133", "טראומת אובדן", "Loss-Related Trauma", "mental", "chronic",
     "trigger_topics",
     "grief_group;validation;reminiscence;social;creative;spiritual_support",
     "טראומת אובדן - אבל מורכב, תמיכה ארוכת טווח"),

    # ----- GRIEF & LOSS (6) -----
    ("CON134", "אבל חריף", "Acute Grief", "mental", "acute",
     "high_pressure_competitive;competitive",
     "grief_group;social;validation;creative;spiritual_support;family_inclusive",
     "אבל חריף - תמיכה ראשונית, ביטוי, נוכחות"),
    ("CON135", "אבל ממושך", "Prolonged Grief Disorder", "mental", "chronic",
     "high_pressure_competitive;competitive",
     "grief_group;social;validation;meaning_focus;creative;one_on_one",
     "אבל ממושך מעבר ל-6 חודשים - תמיכה מקצועית"),
    ("CON136", "אבל מסובך", "Complicated Grief", "mental", "chronic",
     "high_pressure_competitive;trigger_topics",
     "grief_group;one_on_one;creative;validation;meaning_focus",
     "אבל מסובך - תקיעות, רגשי אשמה, צריך טיפול"),
    ("CON137", "אבל מקדים", "Anticipatory Grief", "mental", "moderate",
     "isolation",
     "grief_group;social;validation;family_inclusive;spiritual_support",
     "אבל מקדים - לפני אובדן צפוי"),
    ("CON138", "אבל מודחק", "Disenfranchised Grief", "mental", "chronic",
     "isolation;intrusive_questions",
     "validation;one_on_one;creative;peer_support",
     "אבל מודחק - אובדן שאינו מקבל הכרה חברתית"),
    ("CON139", "אבל ודיכאון מעורבים", "Mixed Grief & Depression", "mental", "moderate",
     "isolation;trigger_topics",
     "grief_group;social;light_exposure;aerobic_low;creative;validation",
     "אבל + דיכאון - שילוב נפוץ, גישה כפולה"),

    # ----- OCD SPECTRUM (5) -----
    ("CON140", "OCD קל", "Mild OCD", "mental", "mild",
     "time_pressure",
     "mindfulness;structured_routine;creative;breathing",
     "OCD קל - מבנה, מיינדפולנס"),
    ("CON141", "OCD בינוני", "Moderate OCD", "mental", "moderate",
     "time_pressure;sudden_changes",
     "mindfulness;structured_routine;creative;breathing;predictable_routine",
     "OCD בינוני - שגרה צפויה, ביטוי יצירתי"),
    ("CON142", "אגרנות", "Hoarding Disorder", "mental", "chronic",
     "intrusive_questions;sudden_changes",
     "one_on_one;validation;creative;structured_routine",
     "אגרנות - גישה לא-שיפוטית, סבלנות"),
    ("CON143", "אקסקוריאציה (גירוד עור)", "Excoriation Disorder", "mental", "moderate",
     "isolation",
     "mindfulness;fine_motor;creative;sensory_stim;relaxation",
     "גירוד אובססיבי - הסחה במוטוריקה עדינה"),
    ("CON144", "טריקוטילומניה", "Trichotillomania", "mental", "moderate",
     "isolation",
     "mindfulness;fine_motor;creative;sensory_stim;relaxation",
     "משיכת שיער - הסחה, מיינדפולנס"),

    # ----- BIPOLAR SPECTRUM (5) -----
    ("CON145", "ביפולר 1", "Bipolar I Disorder", "mental", "chronic",
     "sleep_disruption;over_stimulation;loud_crowds",
     "structured_routine;social;light_exposure;sleep_hygiene;mindfulness",
     "ביפולר 1 - עם פרקי מאניה, יציבות חיונית"),
    ("CON146", "ביפולר 2", "Bipolar II Disorder", "mental", "chronic",
     "sleep_disruption;over_stimulation",
     "structured_routine;social;light_exposure;sleep_hygiene;creative",
     "ביפולר 2 - היפומאניה ודיכאון"),
    ("CON147", "ציקלותימיה", "Cyclothymic Disorder", "mental", "chronic",
     "sleep_disruption",
     "structured_routine;social;sleep_hygiene;mindfulness;light_exposure",
     "ציקלותימיה - תנודות מצב רוח קלות"),
    ("CON148", "אפיזודה מעורבת", "Mixed Episode", "mental", "acute",
     "sleep_disruption;over_stimulation;competitive",
     "one_on_one;structured_routine;mindfulness;soothing_voice;sleep_hygiene",
     "אפיזודה מעורבת - דיכאון+מאניה, יציבות הכרחית"),
    ("CON149", "מחזוריות מהירה", "Rapid Cycling Bipolar", "mental", "chronic",
     "sleep_disruption;over_stimulation",
     "structured_routine;sleep_hygiene;mindfulness;predictable_routine",
     "מחזוריות מהירה - >4 אפיזודות/שנה"),

    # ----- PSYCHOTIC (6) -----
    ("CON150", "סכיזופרניה מוקדמת", "Early-Stage Schizophrenia", "mental", "chronic",
     "over_stimulation;loud_crowds;trigger_topics",
     "one_on_one;structured_routine;sensory_stim;creative;medication_adherence",
     "סכיזופרניה מוקדמת - מבנה, גירוי מבוקר"),
    ("CON151", "סכיזופרניה כרונית", "Chronic Schizophrenia", "mental", "chronic",
     "over_stimulation;loud_crowds;trigger_topics;complex_instructions",
     "one_on_one;structured_routine;sensory_stim;art_therapy;music_familiar",
     "סכיזופרניה כרונית - שגרה פשוטה, גירוי חושי"),
    ("CON152", "סכיזואפקטיבי", "Schizoaffective Disorder", "mental", "chronic",
     "over_stimulation;trigger_topics",
     "structured_routine;light_exposure;social_supervised;creative;mindfulness",
     "סכיזואפקטיבי - תסמיני פסיכוזה + מצב רוח"),
    ("CON153", "סכיזופרניה גיל מאוחר", "Late-Onset Schizophrenia", "mental", "chronic",
     "over_stimulation;intrusive_questions",
     "one_on_one;structured_routine;social_supervised;sensory_stim;validation",
     "סכיזופרניה בגיל מבוגר - לעיתים פרנואידי"),
    ("CON154", "הפרעה דלוזיונלית", "Delusional Disorder", "mental", "chronic",
     "intrusive_questions;trigger_topics",
     "one_on_one;validation;structured_routine;creative",
     "הפרעה דלוזיונלית - מחשבות שווא ממוקדות"),
    ("CON155", "אפיזודה פסיכוטית קצרה", "Brief Psychotic Episode", "mental", "acute",
     "over_stimulation;loud_crowds",
     "one_on_one;structured_routine;sensory_stim;soothing_voice",
     "אפיזודה פסיכוטית קצרה - סביבה רגועה ובטוחה"),

    # ----- SLEEP-RELATED (5) -----
    ("CON156", "נדודי שינה", "Insomnia Disorder", "mental", "chronic",
     "caffeine_late_day;nighttime_activity;sleep_disruption",
     "sleep_hygiene;daytime_activity;light_exposure;aerobic_low;mindfulness",
     "נדודי שינה - היגיינת שינה, פעילות יום"),
    ("CON157", "היפרסומניה", "Hypersomnia", "mental", "chronic",
     "darkness;sleep_disruption",
     "light_exposure;daytime_activity;social;aerobic_low;structured_routine",
     "ישנוניות יתר - גירוי במהלך היום"),
    ("CON158", "הפרעת סיוטים", "Nightmare Disorder", "mental", "chronic",
     "trigger_topics;evening_meals",
     "sleep_hygiene;mindfulness;art_therapy;relaxation;soothing_voice",
     "סיוטים - הרפיה לפני שינה"),
    ("CON159", "הפרעת התנהגות REM", "REM Sleep Behavior Disorder", "mental", "chronic",
     "sleep_disruption",
     "sleep_hygiene;safe_environment;mindfulness",
     "תנועות אלימות בשינה - לעיתים סימן מקדים לפרקינסון"),
    ("CON160", "חרדת שינה", "Sleep-Related Anxiety", "mental", "moderate",
     "evening_meals;trigger_topics;nighttime_activity",
     "sleep_hygiene;mindfulness;breathing;relaxation;soothing_voice",
     "חרדת שינה - הרפיה, היגיינת שינה"),

    # ----- COGNITIVE-EMOTIONAL (6) -----
    ("CON161", "אפתיה", "Apathy Syndrome", "mental", "chronic",
     "alone_extended",
     "social;behavioral_activation;structured_routine;sensory_stim;family_inclusive",
     "אפתיה - חוסר מוטיבציה, הפעלה עדינה"),
    ("CON162", "לחץ דם רגשי (PBA)", "Pseudobulbar Affect", "mental", "chronic",
     "embarrassment_focus",
     "validation;mindfulness;social;creative",
     "PBA - בכי/צחוק לא מבוקר, תיקוף וקבלה"),
    ("CON163", "שקיעת ערב (Sundowning)", "Sundowning", "mental", "chronic",
     "evening_activity;darkness;over_stimulation",
     "structured_routine;light_exposure_evening;soothing_voice;music_familiar;sensory_stim",
     "בלבול ערב - שגרה מובנית, אור עקיף"),
    ("CON164", "תסמונת בדידות", "Loneliness Syndrome", "mental", "chronic",
     "alone_extended;isolation",
     "social;peer_visits;phone_calls;pet_companionship;group_activity;family_inclusive",
     "בדידות כתסמונת - חיבור חברתי קבוע"),
    ("CON165", "דה-מורליזציה", "Demoralization Syndrome", "mental", "chronic",
     "isolation;competitive",
     "meaning_focus;hope_focus;spiritual_support;social;one_on_one",
     "דה-מורליזציה - אובדן תקווה ומשמעות"),
    ("CON166", "מצוקה קיומית", "Existential Distress", "mental", "chronic",
     "trigger_topics;isolation",
     "meaning_focus;spiritual_support;creative;reminiscence;one_on_one",
     "מצוקה קיומית - שאלות חיים, משמעות"),

    # ----- SUBSTANCE-RELATED (6) -----
    ("CON167", "אלכוהוליזם קל", "Mild Alcohol Use Disorder", "mental", "mild",
     "alcohol_present;isolation",
     "social;structured_routine;peer_support;creative;aerobic_low",
     "שימוש קל באלכוהול - תמיכה ושגרה"),
    ("CON168", "אלכוהוליזם בינוני", "Moderate Alcohol Use Disorder", "mental", "moderate",
     "alcohol_present;isolation;trigger_topics",
     "social;structured_routine;peer_support;one_on_one;mindfulness;family_inclusive",
     "שימוש בינוני באלכוהול - תוכנית טיפול"),
    ("CON169", "תלות בבנזודיאזפינים", "Benzodiazepine Dependence", "mental", "chronic",
     "high_balance_demand",
     "structured_routine;social;mindfulness;breathing;gradual_taper_support",
     "תלות בכדורי הרגעה - הפחתה הדרגתית"),
    ("CON170", "תלות באופיואידים", "Opioid Use Disorder", "mental", "chronic",
     "high_balance_demand",
     "structured_routine;social;peer_support;mindfulness;pain_alt_methods",
     "תלות באופיואידים - תמיכה רב-תחומית"),
    ("CON171", "תלות בניקוטין", "Nicotine Dependence", "mental", "chronic",
     "",
     "structured_routine;social;mindfulness;breathing;peer_support",
     "תלות בניקוטין - תמיכה בגמילה"),
    ("CON172", "חרדה מקפאין יתר", "Caffeine Excess Anxiety", "mental", "mild",
     "caffeine_late_day",
     "structured_meals;mindfulness;sleep_hygiene;breathing",
     "חרדה מקפאין - הגבלה והפחתה הדרגתית"),

    # ----- PERSONALITY (7) -----
    ("CON173", "פטרן הימנעותי", "Avoidant Personality Pattern", "mental", "chronic",
     "large_groups;competitive;intrusive_questions",
     "one_on_one;peer_visits;creative;structured_routine;social_supervised",
     "פטרן הימנעותי - בנייה הדרגתית של ביטחון"),
    ("CON174", "פטרן תלותי", "Dependent Personality Pattern", "mental", "chronic",
     "alone_extended",
     "structured_routine;peer_support;one_on_one;family_inclusive;skill_building",
     "פטרן תלותי - חיזוק עצמאות הדרגתי"),
    ("CON175", "פגיעות נרקיסיסטית", "Narcissistic Vulnerability", "mental", "chronic",
     "intrusive_questions;competitive_loss",
     "validation;creative;skill_recognition;peer_support",
     "פגיעות נרקיסיסטית - תיקוף עם גבולות"),
    ("CON176", "פטרן פרנואידי", "Paranoid Personality Pattern", "mental", "chronic",
     "intrusive_questions;trigger_topics;unfamiliar_people",
     "one_on_one;structured_routine;predictable_routine;validation",
     "פטרן פרנואידי - אמון בונים לאט"),
    ("CON177", "פטרן סכיזואידי", "Schizoid Personality Pattern", "mental", "chronic",
     "large_groups;crowded_space",
     "one_on_one;creative;structured_routine;quiet_activities",
     "פטרן סכיזואידי - העדפת בדידות, פעילויות שקטות"),
    ("CON178", "תכונות גבול (BPD)", "Borderline Features", "mental", "chronic",
     "trigger_topics;intrusive_questions;sudden_changes",
     "structured_routine;validation;art_therapy;mindfulness;one_on_one;predictable_routine",
     "תכונות גבול - תיקוף + מיומנויות DBT"),
    ("CON179", "פטרן OCPD", "Obsessive-Compulsive Personality", "mental", "chronic",
     "sudden_changes;disorder_environment",
     "structured_routine;creative;mindfulness;flexibility_practice",
     "OCPD - אישיות נוקשה, גמישות הדרגתית"),

    # ----- IDENTITY & MEANING (5) -----
    ("CON180", "משבר זהות אחרי פרישה", "Post-Retirement Identity Crisis", "mental", "transitional",
     "isolation",
     "meaning_focus;creative;peer_support;skill_recognition;family_inclusive",
     "משבר זהות לאחר פרישה - מציאת משמעות חדשה"),
    ("CON181", "אובדן תפקיד", "Role Loss Adjustment", "mental", "transitional",
     "isolation",
     "meaning_focus;creative;peer_support;volunteer_options;family_inclusive",
     "אובדן תפקיד - מנהל/הורה/וכו"),
    ("CON182", "דיספוריה של דימוי גוף", "Body Image Dysphoria", "mental", "chronic",
     "intrusive_questions;mirror_focus",
     "creative;mindfulness;peer_support;social",
     "דיספוריה גוף - תיקוף, פעילות יוצרת"),
    ("CON183", "מצוקה רוחנית", "Spiritual Distress", "mental", "chronic",
     "trigger_topics",
     "spiritual_support;meaning_focus;religious_appropriate;one_on_one;creative",
     "מצוקה רוחנית - שאלות אמונה ומשמעות"),
    ("CON184", "בידוד קיומי", "Existential Isolation", "mental", "chronic",
     "isolation;trigger_topics",
     "meaning_focus;social;peer_support;creative;spiritual_support",
     "בידוד קיומי - תחושה של אי-הבנה עמוקה"),

    # ----- STRESS-RELATED (5) -----
    ("CON185", "שחיקת מטפל (המטופל כמטפל)", "Caregiver Burnout (Elder as Caregiver)", "mental", "chronic",
     "isolation;high_pressure_competitive",
     "social;respite_options;peer_support;family_inclusive;mindfulness",
     "שחיקה כמטפל - גם דיירים מטפלים, צריך תמיכה"),
    ("CON186", "סטרס כרוני", "Chronic Stress", "mental", "chronic",
     "time_pressure;over_stimulation",
     "mindfulness;breathing;yoga;nature_exposure;structured_routine;social",
     "סטרס כרוני - השפעה גופנית ונפשית"),
    ("CON187", "הסתגלות לאשפוז", "Hospitalization Adjustment", "mental", "acute",
     "sudden_changes;loud_crowds",
     "family_inclusive;social;creative;reminiscence;sensory_stim;predictable_routine",
     "הסתגלות לאשפוז - תמיכה מצרכים בסיסיים"),
    ("CON188", "סטרס מעבר דירה", "Relocation Stress (Transferitis)", "mental", "transitional",
     "sudden_changes;isolation;unfamiliar_people",
     "structured_routine;family_inclusive;creative;reminiscence;peer_support;social",
     "סטרס מעבר - דיור חדש מערער"),
    ("CON189", "הסתגלות למוסד", "Institutionalization Adjustment", "mental", "transitional",
     "sudden_changes;unfamiliar_people;authoritarian_settings",
     "structured_routine;social;family_inclusive;creative;reminiscence;peer_support",
     "הסתגלות למוסד - תהליך ארוך, תמיכה אינטנסיבית"),

    # ----- COMBINED AFFECTIVE (5) -----
    ("CON190", "אפתיה + דיכאון", "Apathy with Depression", "mental", "chronic",
     "alone_extended;isolation",
     "social;light_exposure;behavioral_activation;sensory_stim;structured_routine;family_inclusive",
     "אפתיה+דיכאון - פעם נפוצה בדיירים"),
    ("CON191", "דיכאון חרדתי", "Anxious Depression", "mental", "moderate",
     "isolation;competitive;loud_crowds",
     "social;light_exposure;breathing;mindfulness;structured_routine;creative",
     "דיכאון חרדתי - מצב מעורב, מבנה והרפיה"),
    ("CON192", "דיכאון אגיטטיבי", "Agitated Depression", "mental", "moderate",
     "over_stimulation;competitive;trigger_topics",
     "mindfulness;breathing;structured_routine;gentle_movement;one_on_one",
     "דיכאון אגיטטיבי - אי שקט, הרפיה ופעילות עדינה"),
    ("CON193", "דיכאון מלנכולי", "Melancholic Depression", "mental", "severe",
     "isolation;over_stimulation",
     "social;light_exposure;structured_routine;one_on_one;creative;aerobic_low",
     "דיכאון מלנכולי - אנהדוניה עמוקה"),
    ("CON194", "דיכאון אטיפי בדיירים", "Atypical Late-Life Depression", "mental", "chronic",
     "isolation;medical_focus",
     "social;light_exposure;aerobic_low;reminiscence;family_inclusive;structured_routine",
     "דיכאון אטיפי בדיירים - תלונות גופניות מרובות"),

    # ----- BEHAVIORAL STATES (5) -----
    ("CON195", "התכנסות חברתית קיצונית", "Severe Social Withdrawal", "mental", "chronic",
     "large_groups;crowded_space",
     "one_on_one;peer_visits;creative;sensory_stim;family_inclusive;phone_calls",
     "התכנסות חברתית - חזרה הדרגתית למפגשים"),
    ("CON196", "אנהדוניה", "Anhedonia", "mental", "chronic",
     "alone_extended",
     "behavioral_activation;sensory_stim;creative;social;reminiscence;music_familiar",
     "אנהדוניה - חוסר עונג, חזרה הדרגתית להנאות"),
    ("CON197", "תסמונת חוסר תקווה", "Hopelessness Syndrome", "mental", "severe",
     "isolation;trigger_topics",
     "hope_focus;meaning_focus;one_on_one;social;creative;spiritual_support;family_inclusive",
     "חוסר תקווה - גורם סיכון, התערבות מקצועית"),
    ("CON198", "מחשבות אובדניות כרוניות (סף נמוך)", "Chronic Low-Level Suicidal Ideation", "mental", "chronic",
     "isolation;trigger_topics;alone_extended",
     "one_on_one;social;hope_focus;meaning_focus;family_inclusive;spiritual_support;crisis_plan",
     "מחשבות אובדניות כרוניות - מעקב צמוד, תוכנית משבר"),
    ("CON199", "תסמונת הזנחה עצמית", "Self-Neglect Syndrome", "mental", "chronic",
     "isolation;alone_extended",
     "structured_routine;social;skill_building;family_inclusive;peer_support;sensory_stim",
     "הזנחה עצמית - שכיח בדיירים בודדים, גישה רב-תחומית"),
]
pd.DataFrame(conditions, columns=[
    "code", "name_he", "name_en", "dimension",
    "severity", "limitations", "needs_strengthening", "description_he",
]).to_excel(OUT_DIR / "conditions.xlsx", index=False)


# --- 4. ACTIVITIES ----------------------------------------------------------
# strengthens / addresses_needs match against "needs_strengthening" tags above.
# contraindications match against "limitations" tags above — but kept narrow
# so most activities are eligible for most elders. Hard safety contras only.
activities = [
    # code, name_he, name_en, category, subcategory, strengthens, contraindications,
    # min_capability, duration_min, group_min, group_max, indoor_outdoor, description
    ("ACT001", "הליכה מתונה בקבוצה", "Moderate group walk", "physical", "aerobic",
     "aerobic_low;social;light_exposure;daily_movement;balanced_diet",
     "",
     2, 30, 3, 12, "outdoor",
     "הליכה במתחם בקבוצה קטנה - אירובי קל, חברתי, חשיפה לאור"),
    ("ACT002", "התעמלות בישיבה", "Chair-based exercise", "physical", "strength_flex",
     "range_of_motion;upper_body_low;quadriceps_strength;flexibility;weight_bearing_low",
     "",
     1, 25, 1, 20, "indoor",
     "תרגילים בכיסא - חיזוק עליון, גמישות, נושא משקל קל"),
    ("ACT003", "התעמלות במים", "Water aerobics", "physical", "aerobic",
     "swimming;water_aerobics;quadriceps_strength;range_of_motion;aerobic_low",
     "",
     2, 40, 4, 15, "indoor",
     "פעילות במים - אופטימלי לברכיים, אירובי קל"),
    ("ACT004", "תרגילי איזון", "Balance training", "physical", "balance",
     "balance;weight_bearing_low;gait_training;flexibility",
     "",
     2, 20, 1, 10, "indoor",
     "תרגילי איזון - מומלץ לפרקינסון, אוסטאופורוזיס"),
    ("ACT005", "טאי צ'י", "Tai Chi", "physical", "mind_body",
     "balance;rhythmic_movement;flexibility;mindfulness;breathing;relaxation",
     "",
     2, 45, 3, 15, "indoor",
     "טאי צ'י - איזון, גמישות, מיינדפולנס"),
    ("ACT006", "יוגה לדיירים", "Senior yoga", "physical", "mind_body",
     "flexibility;breathing;relaxation;yoga;mindfulness;range_of_motion",
     "",
     2, 45, 3, 15, "indoor",
     "יוגה מותאמת - גמישות, נשימה, הרפיה"),
    ("ACT007", "תרגילי נשימה", "Breathing exercises", "physical", "respiratory",
     "breathing;pursed_lip;relaxation;mindfulness",
     "",
     1, 15, 1, 15, "indoor",
     "תרגילי נשימה - לכל מצב, מיוחד ל-COPD, חרדה"),
    ("ACT008", "תרגילי שפה ודיבור", "Speech exercises", "physical", "speech",
     "speech_therapy;voice_exercise",
     "",
     1, 20, 1, 8, "indoor",
     "תרגילי דיבור וקול - אחרי שבץ, פרקינסון"),

    ("ACT009", "משחקי זיכרון", "Memory games", "cognitive", "memory",
     "memory_games;moderate_cognitive;complex_cognitive;learning_new",
     "complex_instructions",
     2, 30, 1, 10, "indoor",
     "משחקי זיכרון - גירוי קוגניטיבי"),
    ("ACT010", "פאזלים ותשבצים", "Puzzles & crosswords", "cognitive", "problem_solving",
     "moderate_cognitive;complex_cognitive",
     "complex_instructions",
     2, 30, 1, 5, "indoor",
     "פאזלים, תשבצים, סודוקו"),
    ("ACT011", "טיפול בזיכרונות (רמיניסנציה)", "Reminiscence therapy", "cognitive", "memory",
     "reminiscence;reminiscence_careful;social;memory_games",
     "trigger_topics",
     1, 45, 2, 10, "indoor",
     "שיחה על העבר עם עזרים - תמונות, מוסיקת תקופה"),
    ("ACT012", "אומנות ויצירה", "Art & creativity", "cognitive", "creative",
     "creative;art_therapy;mindfulness;social",
     "",
     1, 60, 1, 12, "indoor",
     "ציור, פיסול, קולאז' - ביטוי יצירתי"),
    ("ACT013", "מוסיקה ושירה", "Music & singing", "cognitive", "music",
     "music_therapy;voice_exercise;rhythmic_movement;social;sensory_stim",
     "",
     1, 45, 2, 20, "indoor",
     "שירה בציבור, האזנה, נגינה"),

    ("ACT014", "קבוצת שיחה", "Conversation group", "social", "discussion",
     "social;group_activity;structured_routine;social_engagement",
     "",
     2, 60, 3, 12, "indoor",
     "קבוצת שיחה על נושא יומי"),
    ("ACT015", "מפגש בין-דורי", "Intergenerational meet", "social", "intergenerational",
     "intergenerational;family_inclusive;social;reminiscence",
     "",
     2, 60, 4, 30, "indoor",
     "מפגש עם ילדי גן/סטודנטים"),
    ("ACT016", "טיול קצר", "Short outing", "social", "outing",
     "outings;social;light_exposure;daily_movement;nature_exposure",
     "long_no_bathroom_access",
     2, 90, 2, 10, "outdoor",
     "יציאה לפארק, חנות, בית כנסת"),
    ("ACT017", "ביקור בית של מתנדבים", "Volunteer visit", "social", "visit",
     "social;peer_visits;family_inclusive;peer_family",
     "",
     1, 60, 1, 1, "indoor",
     "ביקור 1-על-1 של מתנדב"),
    ("ACT018", "שיחות וידיאו עם משפחה", "Family video calls", "social", "remote",
     "social;phone_calls;family_inclusive",
     "",
     2, 30, 1, 1, "indoor",
     "שיחת וידיאו עם בני משפחה"),

    ("ACT019", "מיינדפולנס מודרך", "Guided mindfulness", "mental", "meditation",
     "mindfulness;relaxation;breathing",
     "",
     2, 20, 1, 15, "indoor",
     "תרגול קשב מודרך"),
    ("ACT020", "קבוצת תמיכה באבל", "Grief support group", "mental", "support",
     "grief_group;social;validation",
     "high_pressure_competitive",
     3, 75, 4, 10, "indoor",
     "קבוצת תמיכה מקצועית"),
    ("ACT021", "גינון טיפולי", "Therapeutic gardening", "mental", "horticulture",
     "nature_exposure;creative;sensory_stim;daily_movement;light_exposure",
     "",
     2, 45, 1, 8, "outdoor",
     "גינון בערוגות מוגבהות"),
    ("ACT022", "טיפול בעזרת בעלי חיים", "Animal therapy", "mental", "animal",
     "sensory_stim;social;mindfulness;reminiscence_careful",
     "",
     1, 30, 1, 10, "indoor",
     "כלב/חתול טיפולי"),
    ("ACT023", "אמבטיית חושים", "Sensory bath", "mental", "sensory",
     "sensory_stim;passive_motion;mindfulness;relaxation",
     "",
     1, 30, 1, 5, "indoor",
     "חדר חושים - אור, מוסיקה, מגע, ריח"),

    ("ACT024", "פיזיותרפיה פרטנית", "Individual physio", "physical", "therapy",
     "physiotherapy;range_of_motion;gait_training;mirror_therapy;quadriceps_strength",
     "",
     1, 45, 1, 1, "indoor",
     "טיפול פרטני עם פיזיותרפיסט"),
    ("ACT025", "ריפוי בעיסוק", "Occupational therapy", "physical", "therapy",
     "physiotherapy;complex_self_care_alone;structured_routine",
     "",
     1, 45, 1, 1, "indoor",
     "ריפוי בעיסוק - תפקוד יומיומי"),
    ("ACT026", "טיפול בריצפת אגן", "Pelvic floor therapy", "physical", "therapy",
     "pelvic_floor;timed_voiding",
     "",
     2, 30, 1, 1, "indoor",
     "אימון שרירי רצפת אגן"),

    ("ACT027", "תפילה / קריאה דתית", "Religious service", "social", "religious",
     "religious_appropriate;social;routine;reminiscence",
     "",
     1, 45, 1, 50, "indoor",
     "תפילה, לימוד דתי"),
    ("ACT028", "קבוצה בשפת האם", "Native-language group", "social", "language",
     "native_language_group;cultural_familiar;social;arabic_content;language_learning",
     "",
     2, 60, 3, 12, "indoor",
     "פעילות חברתית בשפת האם"),
    ("ACT029", "התעמלות שכל - מוטוריקה עדינה", "Fine motor exercise", "physical", "motor",
     "range_of_motion;quadriceps_strength;tactile",
     "",
     1, 20, 1, 10, "indoor",
     "מוטוריקה עדינה - חרוזים, בצק, כפתורים"),
    ("ACT030", "מפגש 'קפה ועיתון'", "Coffee & news group", "social", "discussion",
     "social;structured_routine;moderate_cognitive;maintain_social",
     "",
     1, 45, 2, 10, "indoor",
     "מפגש בוקר עם קפה, עיתון, דיון"),

    # ============================================================
    # 20 MENTAL HEALTH SPECIALTY ACTIVITIES (ACT031-ACT050)
    # cover tags introduced by the 100 mental conditions
    # ============================================================
    ("ACT031", "שיחה תרפויטית 1-על-1", "One-on-One Therapy Talk",
     "mental", "psychotherapy",
     "one_on_one;validation;hope_focus;meaning_focus;social;mindfulness",
     "",
     2, 60, 1, 1, "indoor",
     "מפגש פרטני עם איש מקצוע - הקשבה פעילה ותיקוף"),

    ("ACT032", "הליכת הפעלה התנהגותית", "Behavioral Activation Walk",
     "mental", "BA",
     "behavioral_activation;aerobic_low;social;light_exposure;daily_movement;structured_routine;hope_focus",
     "",
     2, 60, 1, 4, "outdoor",
     "הליכה מובנת עם דגש על משימת היום ויעדים קטנים - מומלץ לדיכאון"),

    ("ACT033", "שיחת תקווה ומשמעות", "Hope & Meaning Talk",
     "mental", "logotherapy",
     "hope_focus;meaning_focus;one_on_one;validation;spiritual_support;reminiscence;social",
     "trigger_topics",
     2, 60, 1, 6, "indoor",
     "שיחה ממוקדת על הישגים, ערכים, ומקורות תקווה - לוגו-תרפיה"),

    ("ACT034", "טיפול בבעלי חיים פרטני", "Individual Pet Therapy",
     "mental", "pet_therapy",
     "pet_companionship;sensory_stim;social;mindfulness;soothing_voice;one_on_one",
     "",
     1, 60, 1, 2, "indoor",
     "מפגש שקט עם כלב/חתול טיפולי - מומלץ לבדידות, אפתיה, חרדה"),

    ("ACT035", "היגיינת שינה מודרכת", "Guided Sleep Hygiene Routine",
     "mental", "sleep",
     "sleep_hygiene;mindfulness;breathing;relaxation;structured_routine;predictable_routine",
     "",
     1, 60, 1, 8, "indoor",
     "שגרת ערב מובנית להכנה לשינה - אור עמום, נשימה, מתיחות"),

    ("ACT036", "קבוצת תמיכה לחרדה", "Anxiety Support Group",
     "mental", "support_group",
     "peer_support;validation;social;mindfulness;breathing;one_on_one",
     "loud_crowds;competitive",
     3, 60, 3, 8, "indoor",
     "קבוצה מקצועית קטנה - שיתוף, נורמליזציה, כלי התמודדות"),

    ("ACT037", "ספר משמעות חיים", "Life Story Book",
     "mental", "life_review",
     "meaning_focus;reminiscence;creative;family_inclusive;one_on_one;hope_focus",
     "trigger_topics",
     2, 90, 1, 2, "indoor",
     "תיעוד סיפור חיים בכתב/תמונה/אודיו - יוצר משמעות לזיכרון משפחתי"),

    ("ACT038", "שיחה רוחנית/דתית", "Spiritual / Religious Conversation",
     "mental", "spiritual_care",
     "spiritual_support;religious_appropriate;meaning_focus;hope_focus;one_on_one;reminiscence;validation",
     "",
     1, 60, 1, 6, "indoor",
     "שיחה עם כומר/רב/אימאם/מלווה רוחני - תמיכה במשמעות ואמונה"),

    ("ACT039", "ביקור משפחה מובנה", "Structured Family Visit",
     "mental", "family",
     "family_inclusive;social;reminiscence;validation;hope_focus;intergenerational",
     "",
     2, 90, 2, 10, "indoor",
     "ביקור משפחה עם פעילות משותפת מתוכננת (משחק/אלבום/בישול)"),

    ("ACT040", "קבוצת תמיכת עמיתים", "Peer Support Group",
     "mental", "peer_support",
     "peer_support;social;validation;hope_focus;meaning_focus;group_activity",
     "high_pressure_competitive;loud_crowds",
     3, 75, 3, 10, "indoor",
     "קבוצה של בני אותו דור עם חוויות דומות - לעיתים בלי איש מקצוע"),

    ("ACT041", "מוסיקה של פעם", "Familiar Music Session",
     "mental", "music_familiar",
     "music_familiar;music_therapy;reminiscence;sensory_stim;social;soothing_voice",
     "",
     1, 60, 1, 12, "indoor",
     "האזנה ושירה משירי תקופת הצעירות - חיבור רגשי, אפילו בדמנציה"),

    ("ACT042", "עיסוי טיפולי", "Therapeutic Touch & Massage",
     "mental", "touch_therapy",
     "gentle_touch;sensory_stim;relaxation;mindfulness;soothing_voice;one_on_one",
     "",
     1, 60, 1, 1, "indoor",
     "עיסוי עדין של כתפיים/ידיים/רגליים - הרגעה, חיבור גופני בטוח"),

    ("ACT043", "הרגעת ערב לסונדאונינג", "Evening Calming Routine",
     "mental", "sundowning",
     "structured_routine;soothing_voice;music_familiar;sensory_stim;light_exposure_evening;relaxation",
     "",
     1, 60, 1, 4, "indoor",
     "שגרת ערב למניעת בלבול אחר הצהריים - אור עקיף, מוסיקה, פעילות שקטה"),

    ("ACT044", "כתיבת יומן רגשי", "Emotional Journaling",
     "mental", "journaling",
     "self_expression;mindfulness;creative;meaning_focus;hope_focus;one_on_one",
     "",
     1, 60, 1, 1, "indoor",
     "כתיבה חופשית או מודרכת על רגשות, אירועי היום, תודות"),

    ("ACT045", "מיומנויות DBT / ויסות רגשי", "DBT / Emotion Regulation Skills",
     "mental", "DBT",
     "validation;mindfulness;structured_routine;peer_support;social;breathing",
     "high_pressure_competitive",
     3, 75, 3, 8, "indoor",
     "קבוצה ללימוד מיומנויות וויסות רגשי - מומלץ ל-BPD ולחוסר ויסות"),

    ("ACT046", "פעילות גינון משמעותי", "Meaningful Gardening",
     "mental", "horticulture_therapy",
     "nature_exposure;creative;sensory_stim;meaning_focus;hope_focus;daily_movement;light_exposure",
     "",
     2, 60, 1, 6, "outdoor",
     "גינון עם דגש על צמיחה ועוצמת חיים - מומלץ לדיכאון וקיומי"),

    ("ACT047", "מפגש זיכרון חברי בעבר", "Friendship Reminiscence",
     "mental", "social_reminiscence",
     "reminiscence;social;peer_visits;validation;meaning_focus;family_inclusive",
     "trigger_topics",
     2, 60, 1, 6, "indoor",
     "שיחה על חברים מהעבר - חיזוק זהות וקשרים"),

    ("ACT048", "אומנות ביטוי רגשי", "Expressive Art Therapy",
     "mental", "art_therapy",
     "self_expression;creative;art_therapy;validation;mindfulness;one_on_one",
     "",
     1, 60, 1, 6, "indoor",
     "אומנות עם דגש על ביטוי רגשות - לא על תוצאה אסתטית"),

    ("ACT049", "בניית מיומנות חדשה", "New Skill Building",
     "mental", "skill_building",
     "skill_building;skill_recognition;hope_focus;meaning_focus;structured_routine;social",
     "complex_instructions",
     3, 60, 1, 8, "indoor",
     "לימוד מיומנות חדשה (טלפון, אומנות, תחום עניין) - חיזוק יכולת עצמית"),

    ("ACT050", "סקירת תוכנית משבר", "Crisis Plan Review",
     "mental", "crisis",
     "crisis_plan;one_on_one;family_inclusive;validation;hope_focus;structured_routine",
     "",
     2, 60, 1, 1, "indoor",
     "סקירת תוכנית פעולה למצב משבר - אנשי קשר, סימני אזהרה, צעדים"),
]
activities = expand_activities(activities)
# grow the physical-activity pool to 2000 (scheduled heavily by the planner)
activities = ensure_physical_activities(activities, target=2000)
pd.DataFrame(activities, columns=[
    "code", "name_he", "name_en", "category", "subcategory",
    "strengthens", "contraindications",
    "min_capability_level", "duration_min",
    "group_size_min", "group_size_max", "location", "description_he",
]).to_excel(OUT_DIR / "activities.xlsx", index=False)


# --- 5. EXERCISES (strength + aerobic + flexibility/balance) -----------------
# Each row is a single concrete drill with:
#   - target_muscles  : which muscle groups it loads
#   - target_systems  : cardiovascular / musculoskeletal / respiratory / neuro
#   - strengthens     : tag set matching needs_strengthening on diseases
#   - contraindications: tag set matching limitations on diseases (don't do
#                       this exercise if elder has any of these)
#   - intensity       : 1 (very light) ... 5 (vigorous)
#   - min_capability_level : 1 (fully dependent) ... 5 (independent)
#   - position        : standing / sitting / lying / pool
#   - equipment       : none / chair / wall / light_weights / band / pool / treadmill
exercises = [
    # --- STRENGTH (kept LOW intensity, sitting-friendly) ----------------------
    ("EX001", "סקווט בעזרת כיסא", "Chair-assisted squats", "Приседания со стулом",
     "strength", "quadriceps;glutes;hamstrings", "musculoskeletal",
     "quadriceps_strength;weight_bearing_low;balance",
     "deep_squat",
     2, 3, 5, "3 סטים × 8-12 חזרות", "standing", "chair",
     "סקווט קל - יד אחת על כיסא לתמיכה, ירידה רק עד 45 מעלות בברך"),

    ("EX002", "הרמת רגל ישרה בישיבה", "Seated straight leg raises", "Подъём прямой ноги сидя",
     "strength", "quadriceps;hip_flexors", "musculoskeletal",
     "quadriceps_strength;range_of_motion",
     "",
     1, 1, 8, "2 סטים × 10 חזרות לכל רגל", "sitting", "chair",
     "מצוין לדיירים עם אוסטאוארתריטיס בברך - מחזק את שריר הירך הקדמי בלי עומס על מפרק"),

    ("EX003", "שכיבות סמיכה מול קיר", "Wall push-ups", "Отжимания от стены",
     "strength", "chest;triceps;shoulders;core", "musculoskeletal",
     "upper_body_low;range_of_motion",
     "",
     2, 2, 5, "3 סטים × 10 חזרות", "standing", "wall",
     "שכיבות סמיכה קלות מול קיר - מחזק חזה וזרועות, בטוח לדיירים"),

    ("EX004", "כפיפת מרפק עם משקל קל", "Light bicep curls", "Сгибания на бицепс с лёгким весом",
     "strength", "biceps;forearms", "musculoskeletal",
     "upper_body_low",
     "heavy_lifting",
     2, 2, 8, "2 סטים × 12 חזרות (משקל 0.5-1 ק\"ג)", "sitting", "light_weights",
     "מחזק זרועות לפעולות יומיומיות (הרמת תיק, פתיחת דלת)"),

    ("EX005", "משיכה בגומיית התנגדות", "Resistance band rows", "Тяга резинкой",
     "strength", "back;biceps;rhomboids", "musculoskeletal",
     "upper_body_low;range_of_motion",
     "",
     2, 2, 8, "2 סטים × 12 חזרות", "sitting", "band",
     "משיכה לתוך הבטן עם גומייה - חיזוק שרירי גב עליון ויציבה"),

    ("EX006", "כפיפת ברך בישיבה", "Seated knee extensions", "Разгибание колена сидя",
     "strength", "quadriceps", "musculoskeletal",
     "quadriceps_strength",
     "",
     1, 1, 6, "2 סטים × 10 חזרות לכל רגל", "sitting", "chair",
     "ישיבה בכיסא, יישור ברך עד אופקי - מצוין לכאבי ברכיים"),

    ("EX007", "כיווצי שוקיים בעמידה", "Standing calf raises", "Подъём на носки стоя",
     "strength", "calves;ankles", "musculoskeletal",
     "balance;weight_bearing_low",
     "high_balance_demand",
     2, 3, 5, "3 סטים × 15 חזרות", "standing", "chair",
     "עליה על קצות אצבעות בעמידה ליד כיסא - מחזק שוקיים, משפר איזון"),

    ("EX008", "כפיפת בטן קלה בישיבה", "Seated abdominal contractions",
     "Подтягивание живота сидя",
     "strength", "core;abdominals", "musculoskeletal",
     "range_of_motion;balance",
     "",
     1, 1, 5, "10 חזרות איטיות", "sitting", "chair",
     "כווץ בטן עמוקות בנשיפה - מחזק שרירי ליבה, משפר יציבה"),

    ("EX009", "סיבוב כתפיים", "Shoulder rolls",
     "Круговые движения плечами",
     "flexibility", "shoulders;upper_back", "musculoskeletal",
     "range_of_motion;flexibility;upper_body_low",
     "",
     1, 1, 4, "10 קדימה, 10 אחורה", "sitting", "none",
     "סיבוב כתפיים אחורה ולפנים - שחרור כתפיים מתוחות"),

    # --- AEROBIC ----------------------------------------------------------------
    ("EX010", "הליכה מהירה במסדרון", "Brisk corridor walk", "Быстрая ходьба по коридору",
     "aerobic", "lower_body;cardiovascular", "cardiovascular;musculoskeletal",
     "aerobic_low;daily_movement;gait_training",
     "high_intensity",
     3, 3, 15, "15 דקות בקצב שאפשר עוד לדבר", "standing", "none",
     "הליכה במסדרון/חצר בקצב שמעלה דופק ב-20-30 פעימות מהמנוחה"),

    ("EX011", "אופניים נייחים בעומס נמוך", "Stationary bike low-resistance",
     "Велотренажёр на низкой нагрузке",
     "aerobic", "quadriceps;hamstrings;calves;cardiovascular",
     "cardiovascular;musculoskeletal",
     "aerobic_low;quadriceps_strength;daily_movement",
     "high_intensity",
     3, 3, 15, "15 דקות בהילוך נמוך, RPM 50-60", "sitting", "stationary_bike",
     "אופני כושר בעומס נמוך - אירובי חסכוני, מצוין לבעיות ברכיים"),

    ("EX012", "צעדים לצדדים בעזרת כיסא", "Side step-touch with chair support",
     "Шаги в сторону с поддержкой",
     "aerobic", "hip_abductors;cardiovascular;balance",
     "cardiovascular;musculoskeletal",
     "balance;aerobic_low;gait_training",
     "high_balance_demand",
     2, 3, 5, "5 דקות, 30 שניות עבודה / 30 מנוחה", "standing", "chair",
     "צעד ימינה-נגיעה, צעד שמאלה-נגיעה ליד כיסא - מחזק אגן ואיזון"),

    ("EX013", "אירובי בישיבה (תנועות זרועות)", "Seated arm aerobics",
     "Аэробика руками сидя",
     "aerobic", "shoulders;arms;cardiovascular",
     "cardiovascular",
     "aerobic_low;upper_body_low;rhythmic_movement",
     "",
     1, 1, 10, "10 דקות עם מוסיקה - מחיאות, חתירה, אגרופים", "sitting", "none",
     "אירובי בכיסא - אידיאלי למי שלא יכול לעמוד"),

    ("EX014", "הליכה על הליכון בקצב הליכה", "Treadmill walking",
     "Беговая дорожка - ходьба",
     "aerobic", "lower_body;cardiovascular",
     "cardiovascular;musculoskeletal",
     "aerobic_low;gait_training;daily_movement",
     "high_intensity",
     3, 3, 15, "15 דקות, 3.5-4 קמ\"ש, שיפוע 0", "standing", "treadmill",
     "הליכון בקצב הליכה רגיל - דופק בטוח, מאפשר אחיזה ביד"),

    ("EX015", "אירובי במים", "Water aerobics", "Аква-аэробика",
     "aerobic", "full_body;cardiovascular",
     "cardiovascular;musculoskeletal",
     "swimming;water_aerobics;quadriceps_strength;range_of_motion;aerobic_low",
     "",
     2, 3, 20, "20 דקות במים בגובה חזה", "pool", "pool",
     "התעמלות במים - ללא עומס מפרקי, אופטימלי לאוסטאוארתריטיס"),

    ("EX016", "ריקוד למוסיקה איטית", "Slow-music dancing",
     "Танцы под медленную музыку",
     "aerobic", "lower_body;cardiovascular;coordination",
     "cardiovascular;neuro",
     "aerobic_low;rhythmic_movement;balance;social",
     "high_balance_demand",
     2, 2, 10, "10 דקות בקצב מתון", "standing", "none",
     "ריקוד בקצב איטי - אירובי חברתי, גם משפר זיכרון פרוצדורלי"),

    ("EX017", "אופני יד (Arm ergometer)", "Arm ergometer", "Велоэргометр руками",
     "aerobic", "arms;shoulders;cardiovascular",
     "cardiovascular;musculoskeletal",
     "aerobic_low;upper_body_low",
     "",
     2, 2, 12, "12 דקות בעומס מתון", "sitting", "arm_ergometer",
     "אופניים ליד - אירובי לדיירים עם בעיות ברכיים או אי יכולת לעמוד"),

    # --- FLEXIBILITY / BALANCE --------------------------------------------------
    ("EX018", "הליכה עקב-בוהן", "Heel-to-toe walk", "Ходьба пятка-носок",
     "balance", "core;ankles;balance", "neuro;musculoskeletal",
     "balance;gait_training",
     "high_balance_demand",
     2, 3, 5, "10 צעדים בכל כיוון, ליד מעקה", "standing", "wall",
     "תרגיל איזון מתקדם לפרקינסון - חובה ליד מעקה לבטיחות"),

    ("EX019", "מתיחת עורף ירך בישיבה", "Seated hamstring stretch",
     "Растяжка задней поверхности бедра сидя",
     "flexibility", "hamstrings;lower_back",
     "musculoskeletal",
     "flexibility;range_of_motion;relaxation",
     "",
     1, 1, 5, "30 שניות החזקה × 3 חזרות לכל רגל", "sitting", "chair",
     "מתיחה איטית - שיפור גמישות, הפחתת כאב גב"),

    ("EX020", "תרגילי נשימה דיאפרגמטית", "Diaphragmatic breathing",
     "Диафрагмальное дыхание",
     "breathing", "diaphragm;respiratory", "respiratory",
     "breathing;pursed_lip;relaxation;mindfulness",
     "",
     1, 1, 10, "10 דקות, נשימה איטית 4-7-8", "sitting", "none",
     "נשימה עמוקה דרך הסרעפת - מצוין ל-COPD, חרדה, יל\"ד"),
]
exercises = expand_exercises(exercises)
pd.DataFrame(exercises, columns=[
    "code", "name_he", "name_en", "name_ru",
    "type", "target_muscles", "target_systems",
    "strengthens", "contraindications",
    "intensity", "min_capability_level", "duration_min",
    "reps_sets", "position", "equipment", "description_he",
]).to_excel(OUT_DIR / "exercises.xlsx", index=False)


print(f"Wrote knowledge bank files to {OUT_DIR}")
print(f"  diseases.xlsx     - {len(diseases)} rows")
print(f"  medications.xlsx  - {len(medications)} rows")
print(f"  conditions.xlsx   - {len(conditions)} rows")
_phys = sum(1 for r in activities if len(r) > 3 and r[3] == "physical")
print(f"  activities.xlsx   - {len(activities)} rows ({_phys} physical)")
print(f"  exercises.xlsx    - {len(exercises)} rows")
